-- ==========================================
-- 1. Create live_alerts table & Policies
-- ==========================================
CREATE TABLE IF NOT EXISTS public.live_alerts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  link TEXT NOT NULL,
  image_url TEXT,
  is_active BOOLEAN DEFAULT true,
  order_index INT DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

ALTER TABLE public.live_alerts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public read live_alerts" ON public.live_alerts;
CREATE POLICY "Public read live_alerts" ON public.live_alerts FOR SELECT USING (true);

DROP POLICY IF EXISTS "Authenticated insert live_alerts" ON public.live_alerts;
CREATE POLICY "Authenticated insert live_alerts" ON public.live_alerts FOR INSERT WITH CHECK (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Authenticated update live_alerts" ON public.live_alerts;
CREATE POLICY "Authenticated update live_alerts" ON public.live_alerts FOR UPDATE USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Authenticated delete live_alerts" ON public.live_alerts;
CREATE POLICY "Authenticated delete live_alerts" ON public.live_alerts FOR DELETE USING (auth.role() = 'authenticated');

-- ==========================================
-- 2. Verify & Enforce RLS on All Live Tables Safely
-- ==========================================

DO $$ 
BEGIN
  -- deemed_colleges
  IF EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'deemed_colleges') THEN
    EXECUTE 'ALTER TABLE public.deemed_colleges ENABLE ROW LEVEL SECURITY';
    EXECUTE 'DROP POLICY IF EXISTS "Public read deemed_colleges" ON public.deemed_colleges';
    EXECUTE 'CREATE POLICY "Public read deemed_colleges" ON public.deemed_colleges FOR SELECT USING (true)';
    EXECUTE 'DROP POLICY IF EXISTS "Admin write deemed_colleges" ON public.deemed_colleges';
    EXECUTE 'CREATE POLICY "Admin write deemed_colleges" ON public.deemed_colleges USING (auth.role() = ''authenticated'')';
  END IF;

  -- recommended_colleges
  IF EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'recommended_colleges') THEN
    EXECUTE 'ALTER TABLE public.recommended_colleges ENABLE ROW LEVEL SECURITY';
    EXECUTE 'DROP POLICY IF EXISTS "Public read recommended_colleges" ON public.recommended_colleges';
    EXECUTE 'CREATE POLICY "Public read recommended_colleges" ON public.recommended_colleges FOR SELECT USING (true)';
    EXECUTE 'DROP POLICY IF EXISTS "Admin write recommended_colleges" ON public.recommended_colleges';
    EXECUTE 'CREATE POLICY "Admin write recommended_colleges" ON public.recommended_colleges USING (auth.role() = ''authenticated'')';
  END IF;

  -- mbbs_states
  IF EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'mbbs_states') THEN
    EXECUTE 'ALTER TABLE public.mbbs_states ENABLE ROW LEVEL SECURITY';
    EXECUTE 'DROP POLICY IF EXISTS "Public read mbbs_states" ON public.mbbs_states';
    EXECUTE 'CREATE POLICY "Public read mbbs_states" ON public.mbbs_states FOR SELECT USING (true)';
    EXECUTE 'DROP POLICY IF EXISTS "Admin write mbbs_states" ON public.mbbs_states';
    EXECUTE 'CREATE POLICY "Admin write mbbs_states" ON public.mbbs_states USING (auth.role() = ''authenticated'')';
  END IF;

  -- leads
  IF EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'leads') THEN
    EXECUTE 'ALTER TABLE public.leads ENABLE ROW LEVEL SECURITY';
    EXECUTE 'DROP POLICY IF EXISTS "Allow insert leads" ON public.leads';
    EXECUTE 'CREATE POLICY "Allow insert leads" ON public.leads FOR INSERT WITH CHECK (true)';
    EXECUTE 'DROP POLICY IF EXISTS "Admin read/write leads" ON public.leads';
    EXECUTE 'CREATE POLICY "Admin read/write leads" ON public.leads USING (auth.role() = ''authenticated'')';
  END IF;
END $$;

-- ==========================================
-- 3. Create the initial admin user safely
-- ==========================================
-- NOTE: It is highly recommended to use the Supabase Dashboard UI:
-- Go to Authentication -> Users -> Click "Add User" -> "Create User"
-- and create admin@admissionhands.com with your password.
--
-- Alternatively, you can run the SQL block below in the Supabase SQL Editor:
DO $$
DECLARE
  new_user_id uuid := gen_random_uuid();
BEGIN
  IF NOT EXISTS (SELECT 1 FROM auth.users WHERE email = 'admin@admissionhands.com') THEN
    INSERT INTO auth.users (
      id,
      instance_id,
      email,
      encrypted_password,
      email_confirmed_at,
      created_at,
      updated_at,
      aud,
      role,
      raw_app_meta_data,
      raw_user_meta_data,
      is_super_admin
    )
    VALUES (
      new_user_id,
      '00000000-0000-0000-0000-000000000000',
      'admin@admissionhands.com',
      crypt('Admin@12345', gen_salt('bf')),
      now(),
      now(),
      now(),
      'authenticated',
      'authenticated',
      '{"provider":"email","providers":["email"]}'::jsonb,
      '{}'::jsonb,
      false
    );
    
    INSERT INTO auth.identities (
      id,
      user_id,
      identity_data,
      provider,
      last_sign_in_at,
      created_at,
      updated_at,
      provider_id
    )
    VALUES (
      gen_random_uuid(),
      new_user_id,
      format('{"sub":"%s","email":"%s"}', new_user_id::text, 'admin@admissionhands.com')::jsonb,
      'email',
      now(),
      now(),
      now(),
      'admin@admissionhands.com'
    );
  END IF;
END $$;

-- ==========================================
-- 4. Reload Schema Cache
-- ==========================================
NOTIFY pgrst, 'reload schema';
