const fs = require('fs');
const path = require('path');
const dataPath = path.join(__dirname, 'pg_colleges_data.json');
const existing = JSON.parse(fs.readFileSync(dataPath, 'utf-8'));

const moreStates = [
  {"state":"Karnataka","colleges":[
    {"college_name":"AIIMS Raichur","city":"Raichur","college_type":"Government","ownership":"Central Govt (INI)","year_established":2020,"total_pg_seats":20,"key_specialties":["MD Community Medicine","MD Anatomy","MD Physiology"],"short_description":"A newly established AIIMS with modern infrastructure."},
    {"college_name":"Bangalore Medical College and Research Institute","city":"Bengaluru","college_type":"Government","ownership":"State Govt","year_established":1955,"total_pg_seats":300,"key_specialties":["MD Medicine","MS Surgery","MD Radiology"],"short_description":"One of the top government medical colleges in India located in Bengaluru."},
    {"college_name":"Mysore Medical College and Research Institute","city":"Mysuru","college_type":"Government","ownership":"State Govt","year_established":1924,"total_pg_seats":250,"key_specialties":["MD Medicine","MS Surgery","MD Pediatrics"],"short_description":"A prestigious government medical college with rich academic legacy."},
    {"college_name":"Karnataka Institute of Medical Sciences","city":"Hubballi","college_type":"Government","ownership":"State Govt","year_established":1957,"total_pg_seats":220,"key_specialties":["MD Medicine","MS Surgery","MD Radiology"],"short_description":"A leading government institute in North Karnataka."},
    {"college_name":"Mandya Institute of Medical Sciences","city":"Mandya","college_type":"Government","ownership":"State Govt","year_established":2005,"total_pg_seats":150,"key_specialties":["MD Medicine","MS Surgery","MD Obstetrics & Gynecology"],"short_description":"A well-established government college with consistent academic growth."},
    {"college_name":"Vijayanagara Institute of Medical Sciences","city":"Ballari","college_type":"Government","ownership":"State Govt","year_established":1961,"total_pg_seats":180,"key_specialties":["MD Medicine","MS Surgery","MD Pediatrics"],"short_description":"A reputed government institution serving North Karnataka."},
    {"college_name":"Belagavi Institute of Medical Sciences","city":"Belagavi","college_type":"Government","ownership":"State Govt","year_established":2006,"total_pg_seats":140,"key_specialties":["MD Medicine","MS Surgery","MD Anesthesia"],"short_description":"A government college with growing academic reputation."},
    {"college_name":"Shimoga Institute of Medical Sciences","city":"Shivamogga","college_type":"Government","ownership":"State Govt","year_established":2005,"total_pg_seats":140,"key_specialties":["MD Medicine","MS Surgery","MD Pathology"],"short_description":"A developing government college with good academic structure."},
    {"college_name":"Bidar Institute of Medical Sciences","city":"Bidar","college_type":"Government","ownership":"State Govt","year_established":2007,"total_pg_seats":120,"key_specialties":["MD Medicine","MS Surgery","MD Microbiology"],"short_description":"A government institution with improving academic framework."},
    {"college_name":"ESIC Medical College Bengaluru","city":"Bengaluru","college_type":"Government","ownership":"Central Govt","year_established":2012,"total_pg_seats":150,"key_specialties":["MD Medicine","MS Surgery","MD Dermatology"],"short_description":"A central government institution under ESIC with modern infrastructure."},
    {"college_name":"Shri Atal Bihari Vajpayee Medical College","city":"Bengaluru","college_type":"Government","ownership":"State Govt","year_established":2019,"total_pg_seats":60,"key_specialties":["MD Medicine","MS Surgery","MD Community Medicine"],"short_description":"A newer government medical college with modern infrastructure."},
    {"college_name":"St. John's Medical College","city":"Bengaluru","college_type":"Private","ownership":"Trust","year_established":1963,"total_pg_seats":180,"key_specialties":["MD Medicine","MS Surgery","MD Pediatrics"],"short_description":"One of the top private medical colleges in India."},
    {"college_name":"Kasturba Medical College Manipal","city":"Manipal","college_type":"Deemed","ownership":"Deemed University","year_established":1953,"total_pg_seats":250,"key_specialties":["MD Medicine","MS Surgery","MD Radiology"],"short_description":"A premier deemed medical college under Manipal Academy with global reputation."},
    {"college_name":"Kasturba Medical College Mangaluru","city":"Mangaluru","college_type":"Deemed","ownership":"Deemed University","year_established":1955,"total_pg_seats":220,"key_specialties":["MD Medicine","MS Surgery","MD Pediatrics"],"short_description":"A highly reputed deemed institution with strong academic standards."},
    {"college_name":"JSS Medical College","city":"Mysuru","college_type":"Deemed","ownership":"Deemed University","year_established":1984,"total_pg_seats":200,"key_specialties":["MD Medicine","MS Surgery","MD Radiology"],"short_description":"A well-known deemed medical college with strong academic performance."},
    {"college_name":"Jawaharlal Nehru Medical College Belagavi","city":"Belagavi","college_type":"Deemed","ownership":"Deemed University","year_established":1963,"total_pg_seats":220,"key_specialties":["MD Medicine","MS Surgery","MD Pediatrics"],"short_description":"A reputed deemed university under KLE with strong academic reputation."},
    {"college_name":"MS Ramaiah Medical College","city":"Bengaluru","college_type":"Private","ownership":"Trust","year_established":1979,"total_pg_seats":200,"key_specialties":["MD Medicine","MS Surgery","MD Radiology"],"short_description":"A top private medical college with strong academic and clinical reputation."},
    {"college_name":"Kempegowda Institute of Medical Sciences","city":"Bengaluru","college_type":"Private","ownership":"Trust","year_established":1980,"total_pg_seats":180,"key_specialties":["MD Medicine","MS Surgery","MD Pediatrics"],"short_description":"A well-established private institution with strong academic results."},
    {"college_name":"Vydehi Institute of Medical Sciences","city":"Bengaluru","college_type":"Private","ownership":"Trust","year_established":2000,"total_pg_seats":180,"key_specialties":["MD Medicine","MS Surgery","MD Radiology"],"short_description":"A reputed private college with modern infrastructure."},
    {"college_name":"BGS Global Institute of Medical Sciences","city":"Bengaluru","college_type":"Private","ownership":"Trust","year_established":2013,"total_pg_seats":120,"key_specialties":["MD Medicine","MS Surgery","MD Dermatology"],"short_description":"A growing private institution with modern infrastructure."},
    {"college_name":"AJ Institute of Medical Sciences","city":"Mangaluru","college_type":"Private","ownership":"Trust","year_established":2002,"total_pg_seats":150,"key_specialties":["MD Medicine","MS Surgery","MD Radiology"],"short_description":"A well-known private college in coastal Karnataka."},
    {"college_name":"Father Muller Medical College","city":"Mangaluru","college_type":"Private","ownership":"Trust","year_established":1999,"total_pg_seats":150,"key_specialties":["MD Medicine","MS Surgery","MD Dermatology"],"short_description":"A reputed private institution known for strong clinical departments."},
    {"college_name":"SDM College of Medical Sciences","city":"Dharwad","college_type":"Private","ownership":"Trust","year_established":2003,"total_pg_seats":150,"key_specialties":["MD Medicine","MS Surgery","MD Pediatrics"],"short_description":"A well-established private college with strong academic performance."},
    {"college_name":"S. Nijalingappa Medical College","city":"Bagalkot","college_type":"Private","ownership":"Trust","year_established":2002,"total_pg_seats":120,"key_specialties":["MD Medicine","MS Surgery","MD Pathology"],"short_description":"A private medical college with steady academic growth."},
    {"college_name":"Navodaya Medical College","city":"Raichur","college_type":"Private","ownership":"Trust","year_established":2001,"total_pg_seats":140,"key_specialties":["MD Medicine","MS Surgery","MD Pediatrics"],"short_description":"A well-known private institution in North Karnataka."},
    {"college_name":"KVG Medical College","city":"Sullia","college_type":"Private","ownership":"Trust","year_established":2002,"total_pg_seats":100,"key_specialties":["MD Medicine","MS Surgery","MD Microbiology"],"short_description":"A developing private medical college."},
    {"college_name":"Subbaiah Institute of Medical Sciences","city":"Shivamogga","college_type":"Private","ownership":"Trust","year_established":2012,"total_pg_seats":100,"key_specialties":["MD Medicine","MS Surgery","MD Pharmacology"],"short_description":"A private institution with modern infrastructure."},
    {"college_name":"Akash Institute of Medical Sciences","city":"Bengaluru","college_type":"Private","ownership":"Trust","year_established":2016,"total_pg_seats":80,"key_specialties":["MD Medicine","MS Surgery","MD Community Medicine"],"short_description":"A newer private college with modern facilities."},
    {"college_name":"Sri Siddhartha Medical College","city":"Tumakuru","college_type":"Deemed","ownership":"Deemed University","year_established":1988,"total_pg_seats":180,"key_specialties":["MD Medicine","MS Surgery","MD Radiology"],"short_description":"A reputed deemed medical college."},
    {"college_name":"Sri Devaraj Urs Medical College","city":"Kolar","college_type":"Deemed","ownership":"Deemed University","year_established":1986,"total_pg_seats":170,"key_specialties":["MD Medicine","MS Surgery","MD Pediatrics"],"short_description":"A well-established deemed university with strong academic reputation."},
    {"college_name":"Adichunchanagiri Institute of Medical Sciences","city":"Mandya","college_type":"Private","ownership":"Trust","year_established":1986,"total_pg_seats":160,"key_specialties":["MD Medicine","MS Surgery","MD Dermatology"],"short_description":"A reputed private medical college."},
    {"college_name":"MVJ Medical College","city":"Bengaluru","college_type":"Private","ownership":"Trust","year_established":2001,"total_pg_seats":120,"key_specialties":["MD Medicine","MS Surgery","MD Pediatrics"],"short_description":"A well-known private institution."},
    {"college_name":"Dr. BR Ambedkar Medical College","city":"Bengaluru","college_type":"Private","ownership":"Trust","year_established":1981,"total_pg_seats":150,"key_specialties":["MD Medicine","MS Surgery","MD Radiology"],"short_description":"A reputed private medical college in Bengaluru."},
    {"college_name":"East Point College of Medical Sciences","city":"Bengaluru","college_type":"Private","ownership":"Trust","year_established":2017,"total_pg_seats":90,"key_specialties":["MD Medicine","MS Surgery","MD Pathology"],"short_description":"A newer private institution with modern infrastructure."}
  ]},
  {"state":"Kerala","colleges":[
    {"college_name":"Government Medical College Thiruvananthapuram","city":"Thiruvananthapuram","college_type":"Government","ownership":"State Govt","year_established":1951,"total_pg_seats":300,"key_specialties":["MD General Medicine","MS General Surgery","MD Radiology"],"short_description":"The oldest and one of the top government medical colleges in Kerala."},
    {"college_name":"Government Medical College Kozhikode","city":"Kozhikode","college_type":"Government","ownership":"State Govt","year_established":1957,"total_pg_seats":280,"key_specialties":["MD Medicine","MS Surgery","MD Pediatrics"],"short_description":"A premier government medical college in North Kerala."},
    {"college_name":"Government Medical College Kottayam","city":"Kottayam","college_type":"Government","ownership":"State Govt","year_established":1962,"total_pg_seats":220,"key_specialties":["MD Medicine","MS Surgery","MD Obstetrics & Gynecology"],"short_description":"A well-established government institution with consistent academic performance."},
    {"college_name":"Government Medical College Thrissur","city":"Thrissur","college_type":"Government","ownership":"State Govt","year_established":1982,"total_pg_seats":180,"key_specialties":["MD Medicine","MS Surgery","MD Anesthesia"],"short_description":"A reputed government medical college with good academic standards."},
    {"college_name":"Government Medical College Alappuzha","city":"Alappuzha","college_type":"Government","ownership":"State Govt","year_established":2000,"total_pg_seats":150,"key_specialties":["MD Medicine","MS Surgery","MD Pediatrics"],"short_description":"A growing government institution with strong clinical departments."},
    {"college_name":"Government Medical College Ernakulam","city":"Ernakulam","college_type":"Government","ownership":"State Govt","year_established":1999,"total_pg_seats":140,"key_specialties":["MD Medicine","MS Surgery","MD Pathology"],"short_description":"A government medical college located in Kochi region."},
    {"college_name":"Government Medical College Kannur","city":"Kannur","college_type":"Government","ownership":"State Govt","year_established":2006,"total_pg_seats":120,"key_specialties":["MD Medicine","MS Surgery","MD Community Medicine"],"short_description":"A government institution serving North Kerala."},
    {"college_name":"Amrita Institute of Medical Sciences","city":"Kochi","college_type":"Deemed","ownership":"Deemed University","year_established":2002,"total_pg_seats":220,"key_specialties":["MD Medicine","MS Surgery","MD Radiology"],"short_description":"A premier deemed medical university with national reputation."},
    {"college_name":"Pushpagiri Institute of Medical Sciences","city":"Thiruvalla","college_type":"Private","ownership":"Trust","year_established":2002,"total_pg_seats":120,"key_specialties":["MD Medicine","MS Surgery","MD Dermatology"],"short_description":"A reputed private medical college."},
    {"college_name":"MES Medical College","city":"Malappuram","college_type":"Private","ownership":"Trust","year_established":2004,"total_pg_seats":100,"key_specialties":["MD Medicine","MS Surgery","MD Pediatrics"],"short_description":"A private institution with growing academic reputation in Kerala."}
  ]},
  {"state":"Madhya Pradesh","colleges":[
    {"college_name":"AIIMS Bhopal","city":"Bhopal","college_type":"Government","ownership":"Central Govt (INI)","year_established":2012,"total_pg_seats":150,"key_specialties":["MD General Medicine","MS General Surgery","MD Radiology"],"short_description":"An Institute of National Importance with strong academic ecosystem."},
    {"college_name":"Gandhi Medical College Bhopal","city":"Bhopal","college_type":"Government","ownership":"State Govt","year_established":1955,"total_pg_seats":250,"key_specialties":["MD Medicine","MS Surgery","MD Pediatrics"],"short_description":"A premier government medical college with strong academic reputation."},
    {"college_name":"Netaji Subhash Chandra Bose Medical College","city":"Jabalpur","college_type":"Government","ownership":"State Govt","year_established":1955,"total_pg_seats":220,"key_specialties":["MD Medicine","MS Surgery","MD Radiology"],"short_description":"A well-established government institution."},
    {"college_name":"Mahatma Gandhi Memorial Medical College","city":"Indore","college_type":"Government","ownership":"State Govt","year_established":1948,"total_pg_seats":260,"key_specialties":["MD Medicine","MS Surgery","MD Obstetrics & Gynecology"],"short_description":"One of the top government medical colleges in MP."},
    {"college_name":"Gajra Raja Medical College","city":"Gwalior","college_type":"Government","ownership":"State Govt","year_established":1946,"total_pg_seats":200,"key_specialties":["MD Medicine","MS Surgery","MD Pediatrics"],"short_description":"A reputed government college with long-standing academic legacy."},
    {"college_name":"Bundelkhand Medical College","city":"Sagar","college_type":"Government","ownership":"State Govt","year_established":2009,"total_pg_seats":140,"key_specialties":["MD Medicine","MS Surgery","MD Anesthesia"],"short_description":"A growing government institution."},
    {"college_name":"Government Medical College Ratlam","city":"Ratlam","college_type":"Government","ownership":"State Govt","year_established":2018,"total_pg_seats":80,"key_specialties":["MD Medicine","MS Surgery","MD Pathology"],"short_description":"A newer government medical college."},
    {"college_name":"Government Medical College Shivpuri","city":"Shivpuri","college_type":"Government","ownership":"State Govt","year_established":2018,"total_pg_seats":70,"key_specialties":["MD Medicine","MS Surgery","MD Microbiology"],"short_description":"A developing government institution."},
    {"college_name":"Index Medical College","city":"Indore","college_type":"Private","ownership":"Private University","year_established":2006,"total_pg_seats":150,"key_specialties":["MD Medicine","MS Surgery","MD Radiology"],"short_description":"A well-known private medical college."},
    {"college_name":"People's College of Medical Sciences","city":"Bhopal","college_type":"Private","ownership":"Private University","year_established":2005,"total_pg_seats":180,"key_specialties":["MD Medicine","MS Surgery","MD Pediatrics"],"short_description":"Part of People's University with strong academic framework."},
    {"college_name":"LN Medical College","city":"Bhopal","college_type":"Private","ownership":"Trust","year_established":2009,"total_pg_seats":130,"key_specialties":["MD Medicine","MS Surgery","MD Dermatology"],"short_description":"A private medical college with growing academic reputation."},
    {"college_name":"Chirayu Medical College","city":"Bhopal","college_type":"Private","ownership":"Trust","year_established":2011,"total_pg_seats":140,"key_specialties":["MD Medicine","MS Surgery","MD Radiology"],"short_description":"A well-established private institution."},
    {"college_name":"Sri Aurobindo Medical College","city":"Indore","college_type":"Private","ownership":"Private University","year_established":2003,"total_pg_seats":200,"key_specialties":["MD Medicine","MS Surgery","MD Radiology"],"short_description":"A reputed private medical college with advanced infrastructure."},
    {"college_name":"RKDF Medical College","city":"Bhopal","college_type":"Private","ownership":"Private University","year_established":2014,"total_pg_seats":100,"key_specialties":["MD Medicine","MS Surgery","MD Pathology"],"short_description":"A developing private institution."}
  ]}
];

const merged = existing.concat(moreStates);
fs.writeFileSync(dataPath, JSON.stringify(merged, null, 2), 'utf-8');
const total = merged.reduce((acc, s) => acc + s.colleges.length, 0);
console.log(`Merged: ${merged.length} states, ${total} colleges total`);
