// Appends more state data to pg_colleges_data.json
const fs = require('fs');
const path = require('path');
const dataPath = path.join(__dirname, 'pg_colleges_data.json');
const existing = JSON.parse(fs.readFileSync(dataPath, 'utf-8'));

const moreStates = [
  {"state":"Goa","colleges":[{"college_name":"Goa Medical College","city":"Panaji","college_type":"Government","ownership":"State Govt","year_established":1842,"total_pg_seats":180,"key_specialties":["MD General Medicine","MS General Surgery","MD Radiology"],"short_description":"One of the oldest medical colleges in Asia with strong academic legacy."}]},
  {"state":"Gujarat","colleges":[
    {"college_name":"B.J. Medical College","city":"Ahmedabad","college_type":"Government","ownership":"State Govt","year_established":1946,"total_pg_seats":300,"key_specialties":["MD General Medicine","MS General Surgery","MD Radiology"],"short_description":"One of the top government medical colleges in India. Attached Civil Hospital is among the largest in Asia."},
    {"college_name":"Government Medical College Surat","city":"Surat","college_type":"Government","ownership":"State Govt","year_established":1964,"total_pg_seats":220,"key_specialties":["MD Medicine","MS Surgery","MD Pediatrics"],"short_description":"A leading government college with strong academic performance."},
    {"college_name":"Government Medical College Vadodara","city":"Vadodara","college_type":"Government","ownership":"State Govt","year_established":1949,"total_pg_seats":200,"key_specialties":["MD Medicine","MS Orthopedics","MD Anesthesia"],"short_description":"A well-established government institution with strong academic base."},
    {"college_name":"Government Medical College Bhavnagar","city":"Bhavnagar","college_type":"Government","ownership":"State Govt","year_established":1995,"total_pg_seats":150,"key_specialties":["MD Medicine","MS Surgery","MD Pathology"],"short_description":"A reputed government college with consistent PG training programs."},
    {"college_name":"Government Medical College Rajkot","city":"Rajkot","college_type":"Government","ownership":"State Govt","year_established":1995,"total_pg_seats":180,"key_specialties":["MD Medicine","MS Surgery","MD Pediatrics"],"short_description":"A major government medical college in Saurashtra region."},
    {"college_name":"Government Medical College Jamnagar","city":"Jamnagar","college_type":"Government","ownership":"State Govt","year_established":1955,"total_pg_seats":220,"key_specialties":["MD Medicine","MS Surgery","MD Radiology"],"short_description":"A prominent government college with strong academic reputation."},
    {"college_name":"GMERS Medical College Gandhinagar","city":"Gandhinagar","college_type":"Government","ownership":"State Govt","year_established":2012,"total_pg_seats":120,"key_specialties":["MD Medicine","MS Surgery","MD Community Medicine"],"short_description":"Part of the GMERS network with modern infrastructure."},
    {"college_name":"GMERS Medical College Sola","city":"Sola","college_type":"Government","ownership":"State Govt","year_established":2012,"total_pg_seats":110,"key_specialties":["MD Medicine","MS Orthopedics","MD Anesthesia"],"short_description":"A government-supported college in Ahmedabad with good clinical exposure."},
    {"college_name":"GMERS Medical College Vadnagar","city":"Vadnagar","college_type":"Government","ownership":"State Govt","year_established":2017,"total_pg_seats":90,"key_specialties":["MD Medicine","MS Surgery","MD Pharmacology"],"short_description":"A newer GMERS institution with developing PG programs."},
    {"college_name":"GMERS Medical College Himmatnagar","city":"Himmatnagar","college_type":"Government","ownership":"State Govt","year_established":2015,"total_pg_seats":80,"key_specialties":["MD Medicine","MS Surgery","MD Microbiology"],"short_description":"A government-run college with improving academic framework."},
    {"college_name":"GMERS Medical College Junagadh","city":"Junagadh","college_type":"Government","ownership":"State Govt","year_established":2015,"total_pg_seats":80,"key_specialties":["MD Medicine","MS Surgery","MD Pathology"],"short_description":"A developing GMERS college serving Saurashtra region."},
    {"college_name":"GMERS Medical College Dharpur-Patan","city":"Dharpur-Patan","college_type":"Government","ownership":"State Govt","year_established":2012,"total_pg_seats":90,"key_specialties":["MD Medicine","MS Surgery","MD Pediatrics"],"short_description":"A government college with steady academic growth."},
    {"college_name":"Smt. NHL Municipal Medical College","city":"Ahmedabad","college_type":"Government","ownership":"State Govt","year_established":1963,"total_pg_seats":180,"key_specialties":["MD Medicine","MS Surgery","MD Obstetrics & Gynecology"],"short_description":"A reputed municipal medical college with strong academic performance."},
    {"college_name":"Pandit Deendayal Upadhyay Medical College","city":"Rajkot","college_type":"Government","ownership":"State Govt","year_established":1995,"total_pg_seats":160,"key_specialties":["MD Medicine","MS Surgery","MD Radiology"],"short_description":"A leading government college in Rajkot with strong clinical exposure."},
    {"college_name":"MP Shah Medical College","city":"Jamnagar","college_type":"Private","ownership":"Trust","year_established":1955,"total_pg_seats":150,"key_specialties":["MD Medicine","MS Surgery","MD Dermatology"],"short_description":"A reputed private medical college with strong academic history."},
    {"college_name":"SBKS Medical Institute & Research Centre","city":"Vadodara","college_type":"Private","ownership":"Private University","year_established":2003,"total_pg_seats":140,"key_specialties":["MD Medicine","MS Surgery","MD Radiology"],"short_description":"Part of Sumandeep Vidyapeeth with modern infrastructure."},
    {"college_name":"Pramukhswami Medical College","city":"Karamsad","college_type":"Private","ownership":"Private University","year_established":1987,"total_pg_seats":160,"key_specialties":["MD Medicine","MS Surgery","MD Pediatrics"],"short_description":"A well-known private institution under Charutar Arogya Mandal."},
    {"college_name":"C.U. Shah Medical College","city":"Surendranagar","college_type":"Private","ownership":"Trust","year_established":2000,"total_pg_seats":100,"key_specialties":["MD Medicine","MS Surgery","MD Pathology"],"short_description":"A private medical college with growing academic presence."},
    {"college_name":"Zydus Medical College","city":"Dahod","college_type":"Private","ownership":"Trust","year_established":2018,"total_pg_seats":90,"key_specialties":["MD Medicine","MS Surgery","MD Microbiology"],"short_description":"A newer private institution with modern infrastructure."},
    {"college_name":"Parul Institute of Medical Sciences & Research","city":"Vadodara","college_type":"Private","ownership":"Private University","year_established":2016,"total_pg_seats":120,"key_specialties":["MD Medicine","MS Surgery","MD Anesthesia"],"short_description":"Part of Parul University with large campus and modern infrastructure."},
    {"college_name":"GMERS Medical College Valsad","city":"Valsad","college_type":"Government","ownership":"State Govt","year_established":2017,"total_pg_seats":70,"key_specialties":["MD Medicine","MS Surgery","MD Community Medicine"],"short_description":"A developing GMERS college with expanding PG intake."},
    {"college_name":"GMERS Medical College Morbi","city":"Morbi","college_type":"Government","ownership":"State Govt","year_established":2021,"total_pg_seats":50,"key_specialties":["MD Medicine","MD Pharmacology","MD Microbiology"],"short_description":"A newly established government college with initial PG courses."},
    {"college_name":"GMERS Medical College Godhra","city":"Godhra","college_type":"Government","ownership":"State Govt","year_established":2019,"total_pg_seats":60,"key_specialties":["MD Medicine","MS Surgery","MD Pathology"],"short_description":"A relatively new GMERS college with growing academic structure."},
    {"college_name":"Adani Institute of Medical Sciences","city":"Bhuj","college_type":"Private","ownership":"Trust","year_established":2009,"total_pg_seats":110,"key_specialties":["MD Medicine","MS Surgery","MD Pediatrics"],"short_description":"A well-established private medical college in Kutch region."}
  ]},
  {"state":"Haryana","colleges":[
    {"college_name":"AIIMS Jhajjar (National Cancer Institute)","city":"Jhajjar","college_type":"Government","ownership":"Central Govt (INI)","year_established":2018,"total_pg_seats":60,"key_specialties":["MD Radiotherapy","MD Pathology","MD Nuclear Medicine"],"short_description":"Part of AIIMS New Delhi functioning as National Cancer Institute."},
    {"college_name":"Pt. B.D. Sharma PGIMS","city":"Rohtak","college_type":"Government","ownership":"State Govt","year_established":1960,"total_pg_seats":300,"key_specialties":["MD Medicine","MS Surgery","MD Radiology"],"short_description":"The premier government medical institute of Haryana with massive patient inflow."},
    {"college_name":"Kalpana Chawla Government Medical College","city":"Karnal","college_type":"Government","ownership":"State Govt","year_established":2017,"total_pg_seats":100,"key_specialties":["MD Medicine","MS Surgery","MD Pediatrics"],"short_description":"A relatively new government college with modern infrastructure."},
    {"college_name":"Shaheed Hasan Khan Mewati Government Medical College","city":"Nalhar","college_type":"Government","ownership":"State Govt","year_established":2013,"total_pg_seats":90,"key_specialties":["MD Medicine","MS Surgery","MD Community Medicine"],"short_description":"A government college catering to rural population with diverse case mix."},
    {"college_name":"Maharaja Agrasen Medical College","city":"Agroha","college_type":"Private","ownership":"Trust","year_established":2002,"total_pg_seats":120,"key_specialties":["MD Medicine","MS Surgery","MD Radiology"],"short_description":"A well-known private medical college with strong academic programs."},
    {"college_name":"Adesh Medical College & Hospital","city":"Kurukshetra","college_type":"Private","ownership":"Private University","year_established":2017,"total_pg_seats":80,"key_specialties":["MD Medicine","MS Surgery","MD Anesthesia"],"short_description":"A developing private institution with modern infrastructure."},
    {"college_name":"SGT Medical College","city":"Gurugram","college_type":"Private","ownership":"Private University","year_established":2010,"total_pg_seats":150,"key_specialties":["MD Medicine","MS Orthopedics","MD Dermatology"],"short_description":"A reputed private medical college in NCR region with modern infrastructure."}
  ]},
  {"state":"Himachal Pradesh","colleges":[
    {"college_name":"Indira Gandhi Medical College","city":"Shimla","college_type":"Government","ownership":"State Govt","year_established":1966,"total_pg_seats":150,"key_specialties":["MD General Medicine","MS General Surgery","MD Radiology"],"short_description":"A premier government medical college in Himachal Pradesh with strong academic reputation."},
    {"college_name":"Dr. Rajendra Prasad Government Medical College","city":"Tanda","college_type":"Government","ownership":"State Govt","year_established":1996,"total_pg_seats":120,"key_specialties":["MD Medicine","MS Surgery","MD Pediatrics"],"short_description":"A well-established government institution serving northern Himachal Pradesh."},
    {"college_name":"AIIMS Bilaspur","city":"Bilaspur","college_type":"Government","ownership":"Central Govt (INI)","year_established":2017,"total_pg_seats":40,"key_specialties":["MD Community Medicine","MD Anatomy","MD Biochemistry"],"short_description":"An emerging AIIMS institute with modern infrastructure."}
  ]},
  {"state":"Jharkhand","colleges":[
    {"college_name":"AIIMS Deoghar","city":"Deoghar","college_type":"Government","ownership":"Central Govt (INI)","year_established":2019,"total_pg_seats":25,"key_specialties":["MD Community Medicine","MD Anatomy","MD Physiology"],"short_description":"An emerging AIIMS institute with modern infrastructure and evolving academic programs."},
    {"college_name":"Rajendra Institute of Medical Sciences","city":"Ranchi","college_type":"Government","ownership":"State Govt","year_established":1960,"total_pg_seats":180,"key_specialties":["MD General Medicine","MS General Surgery","MD Radiology"],"short_description":"The premier government medical institute of Jharkhand."},
    {"college_name":"MGM Medical College","city":"Jamshedpur","college_type":"Government","ownership":"State Govt","year_established":1961,"total_pg_seats":120,"key_specialties":["MD Medicine","MS Surgery","MD Pediatrics"],"short_description":"A well-established government medical college with good academic standing."}
  ]}
];

const merged = existing.concat(moreStates);
fs.writeFileSync(dataPath, JSON.stringify(merged, null, 2), 'utf-8');
const total = merged.reduce((acc, s) => acc + s.colleges.length, 0);
console.log(`Merged: ${merged.length} states, ${total} colleges total`);
