const fs = require('fs');
const path = require('path');
const dataPath = path.join(__dirname, 'pg_colleges_data.json');
const existing = JSON.parse(fs.readFileSync(dataPath, 'utf-8'));

const moreStates = [
  {"state":"Punjab","colleges":[
    {"college_name":"AIIMS Bathinda","city":"Bathinda","college_type":"Government","ownership":"Central Govt (INI)","year_established":2019,"total_pg_seats":40,"key_specialties":["MD Community Medicine","MD Anatomy","MD Physiology"],"short_description":"A newer AIIMS institute with modern infrastructure."},
    {"college_name":"Government Medical College Amritsar","city":"Amritsar","college_type":"Government","ownership":"State Govt","year_established":1943,"total_pg_seats":220,"key_specialties":["MD Medicine","MS Surgery","MD Pediatrics"],"short_description":"A premier government medical college in Punjab."},
    {"college_name":"Government Medical College Patiala","city":"Patiala","college_type":"Government","ownership":"State Govt","year_established":1953,"total_pg_seats":200,"key_specialties":["MD Medicine","MS Surgery","MD Radiology"],"short_description":"A well-established government institution."},
    {"college_name":"Dayanand Medical College & Hospital","city":"Ludhiana","college_type":"Private","ownership":"Trust","year_established":1964,"total_pg_seats":180,"key_specialties":["MD Medicine","MS Surgery","MD Dermatology"],"short_description":"A reputed private medical college."},
    {"college_name":"Christian Medical College Ludhiana","city":"Ludhiana","college_type":"Private","ownership":"Trust","year_established":1894,"total_pg_seats":160,"key_specialties":["MD Medicine","MS Surgery","MD Pediatrics"],"short_description":"One of the oldest private medical colleges in India."},
    {"college_name":"Adesh Institute of Medical Sciences","city":"Bathinda","college_type":"Private","ownership":"Private University","year_established":2006,"total_pg_seats":120,"key_specialties":["MD Medicine","MS Surgery","MD Radiology"],"short_description":"A private institution with modern infrastructure."}
  ]},
  {"state":"Rajasthan","colleges":[
    {"college_name":"AIIMS Jodhpur","city":"Jodhpur","college_type":"Government","ownership":"Central Govt (INI)","year_established":2012,"total_pg_seats":140,"key_specialties":["MD General Medicine","MS General Surgery","MD Radiology"],"short_description":"An Institute of National Importance with strong academic ecosystem."},
    {"college_name":"SMS Medical College","city":"Jaipur","college_type":"Government","ownership":"State Govt","year_established":1947,"total_pg_seats":300,"key_specialties":["MD Medicine","MS Surgery","MD Pediatrics"],"short_description":"The premier government medical college of Rajasthan."},
    {"college_name":"Dr. S.N. Medical College","city":"Jodhpur","college_type":"Government","ownership":"State Govt","year_established":1965,"total_pg_seats":250,"key_specialties":["MD Medicine","MS Surgery","MD Radiology"],"short_description":"A well-established government institution."},
    {"college_name":"RNT Medical College","city":"Udaipur","college_type":"Government","ownership":"State Govt","year_established":1961,"total_pg_seats":220,"key_specialties":["MD Medicine","MS Surgery","MD Obstetrics & Gynecology"],"short_description":"A major government medical college in southern Rajasthan."},
    {"college_name":"SP Medical College","city":"Bikaner","college_type":"Government","ownership":"State Govt","year_established":1959,"total_pg_seats":200,"key_specialties":["MD Medicine","MS Surgery","MD Pediatrics"],"short_description":"A reputed government college serving northern Rajasthan."},
    {"college_name":"JLN Medical College","city":"Ajmer","college_type":"Government","ownership":"State Govt","year_established":1965,"total_pg_seats":180,"key_specialties":["MD Medicine","MS Surgery","MD Radiology"],"short_description":"A well-established government institution."},
    {"college_name":"RUHS College of Medical Sciences","city":"Jaipur","college_type":"Government","ownership":"State Govt","year_established":2014,"total_pg_seats":120,"key_specialties":["MD Medicine","MS Surgery","MD Community Medicine"],"short_description":"A newer government medical college under RUHS."},
    {"college_name":"Government Medical College Kota","city":"Kota","college_type":"Government","ownership":"State Govt","year_established":1992,"total_pg_seats":150,"key_specialties":["MD Medicine","MS Surgery","MD Pediatrics"],"short_description":"A prominent government institution."},
    {"college_name":"Geetanjali Medical College","city":"Udaipur","college_type":"Private","ownership":"Private University","year_established":2008,"total_pg_seats":150,"key_specialties":["MD Medicine","MS Surgery","MD Radiology"],"short_description":"A reputed private institution."},
    {"college_name":"Pacific Medical College","city":"Udaipur","college_type":"Private","ownership":"Private University","year_established":2014,"total_pg_seats":130,"key_specialties":["MD Medicine","MS Surgery","MD Pediatrics"],"short_description":"A private medical college with modern infrastructure."},
    {"college_name":"NIMS Medical College","city":"Jaipur","college_type":"Private","ownership":"Private University","year_established":2004,"total_pg_seats":180,"key_specialties":["MD Medicine","MS Surgery","MD Radiology"],"short_description":"A well-established private university medical college."}
  ]},
  {"state":"Sikkim","colleges":[
    {"college_name":"Sikkim Manipal Institute of Medical Sciences","city":"Gangtok","college_type":"Private","ownership":"Private University","year_established":2000,"total_pg_seats":80,"key_specialties":["MD General Medicine","MS General Surgery","MD Pediatrics"],"short_description":"A well-established private medical college under Manipal Group."}
  ]},
  {"state":"Tamil Nadu","colleges":[
    {"college_name":"Madras Medical College","city":"Chennai","college_type":"Government","ownership":"State Govt","year_established":1835,"total_pg_seats":350,"key_specialties":["MD General Medicine","MS General Surgery","MD Radiology"],"short_description":"One of the oldest and most prestigious medical colleges in India."},
    {"college_name":"Stanley Medical College","city":"Chennai","college_type":"Government","ownership":"State Govt","year_established":1938,"total_pg_seats":300,"key_specialties":["MD Medicine","MS Surgery","MD Pediatrics"],"short_description":"A premier government medical college in Chennai."},
    {"college_name":"Kilpauk Medical College","city":"Chennai","college_type":"Government","ownership":"State Govt","year_established":1960,"total_pg_seats":280,"key_specialties":["MD Medicine","MS Surgery","MD Obstetrics & Gynecology"],"short_description":"A well-established government institution."},
    {"college_name":"Coimbatore Medical College","city":"Coimbatore","college_type":"Government","ownership":"State Govt","year_established":1966,"total_pg_seats":250,"key_specialties":["MD Medicine","MS Surgery","MD Radiology"],"short_description":"A leading government medical college in western Tamil Nadu."},
    {"college_name":"Madurai Medical College","city":"Madurai","college_type":"Government","ownership":"State Govt","year_established":1954,"total_pg_seats":300,"key_specialties":["MD Medicine","MS Surgery","MD Pediatrics"],"short_description":"A prestigious government institution."},
    {"college_name":"Tirunelveli Medical College","city":"Tirunelveli","college_type":"Government","ownership":"State Govt","year_established":1965,"total_pg_seats":220,"key_specialties":["MD Medicine","MS Surgery","MD Radiology"],"short_description":"A reputed government medical college."},
    {"college_name":"Thanjavur Medical College","city":"Thanjavur","college_type":"Government","ownership":"State Govt","year_established":1959,"total_pg_seats":220,"key_specialties":["MD Medicine","MS Surgery","MD Obstetrics & Gynecology"],"short_description":"A reputed government medical college."},
    {"college_name":"Chengalpattu Medical College","city":"Chengalpattu","college_type":"Government","ownership":"State Govt","year_established":1965,"total_pg_seats":200,"key_specialties":["MD Medicine","MS Surgery","MD Dermatology"],"short_description":"A well-established government institution near Chennai."},
    {"college_name":"Christian Medical College Vellore","city":"Vellore","college_type":"Private","ownership":"Trust","year_established":1900,"total_pg_seats":250,"key_specialties":["MD Medicine","MS Surgery","MD Radiology"],"short_description":"One of the top private medical colleges in India with global reputation."},
    {"college_name":"SRM Medical College","city":"Chennai","college_type":"Deemed","ownership":"Deemed University","year_established":2005,"total_pg_seats":200,"key_specialties":["MD Medicine","MS Surgery","MD Radiology"],"short_description":"A reputed deemed university."},
    {"college_name":"Sri Ramachandra Medical College","city":"Chennai","college_type":"Deemed","ownership":"Deemed University","year_established":1985,"total_pg_seats":250,"key_specialties":["MD Medicine","MS Surgery","MD Pediatrics"],"short_description":"A premier deemed university."},
    {"college_name":"Saveetha Medical College","city":"Chennai","college_type":"Deemed","ownership":"Deemed University","year_established":2008,"total_pg_seats":220,"key_specialties":["MD Medicine","MS Surgery","MD Dermatology"],"short_description":"A leading deemed institution."},
    {"college_name":"Chettinad Hospital & Research Institute","city":"Chennai","college_type":"Deemed","ownership":"Deemed University","year_established":2006,"total_pg_seats":200,"key_specialties":["MD Medicine","MS Surgery","MD Radiology"],"short_description":"A reputed deemed university with modern infrastructure."},
    {"college_name":"Meenakshi Medical College","city":"Kanchipuram","college_type":"Deemed","ownership":"Deemed University","year_established":2003,"total_pg_seats":180,"key_specialties":["MD Medicine","MS Surgery","MD Pediatrics"],"short_description":"A well-established deemed institution."},
    {"college_name":"PSG Institute of Medical Sciences","city":"Coimbatore","college_type":"Private","ownership":"Trust","year_established":1985,"total_pg_seats":180,"key_specialties":["MD Medicine","MS Surgery","MD Radiology"],"short_description":"A reputed private medical college."},
    {"college_name":"Vinayaka Missions Medical College","city":"Salem","college_type":"Deemed","ownership":"Deemed University","year_established":1995,"total_pg_seats":200,"key_specialties":["MD Medicine","MS Surgery","MD Pathology"],"short_description":"A well-known deemed university."}
  ]},
  {"state":"Telangana","colleges":[
    {"college_name":"AIIMS Bibinagar","city":"Bibinagar","college_type":"Government","ownership":"Central Govt (INI)","year_established":2019,"total_pg_seats":40,"key_specialties":["MD Community Medicine","MD Anatomy","MD Physiology"],"short_description":"A newer AIIMS institute with modern infrastructure."},
    {"college_name":"Osmania Medical College","city":"Hyderabad","college_type":"Government","ownership":"State Govt","year_established":1846,"total_pg_seats":300,"key_specialties":["MD General Medicine","MS General Surgery","MD Radiology"],"short_description":"One of the oldest and most prestigious medical colleges in India."},
    {"college_name":"Gandhi Medical College Hyderabad","city":"Hyderabad","college_type":"Government","ownership":"State Govt","year_established":1954,"total_pg_seats":250,"key_specialties":["MD Medicine","MS Surgery","MD Pediatrics"],"short_description":"A premier government medical college in Telangana."},
    {"college_name":"Kakatiya Medical College","city":"Warangal","college_type":"Government","ownership":"State Govt","year_established":1959,"total_pg_seats":200,"key_specialties":["MD Medicine","MS Surgery","MD Obstetrics & Gynecology"],"short_description":"A well-established government institution."},
    {"college_name":"ESIC Medical College Hyderabad","city":"Hyderabad","college_type":"Government","ownership":"Central Govt","year_established":2016,"total_pg_seats":120,"key_specialties":["MD Medicine","MS Surgery","MD Dermatology"],"short_description":"A central government medical college under ESIC."},
    {"college_name":"Kamineni Institute of Medical Sciences","city":"Nalgonda","college_type":"Private","ownership":"Trust","year_established":1999,"total_pg_seats":150,"key_specialties":["MD Medicine","MS Surgery","MD Radiology"],"short_description":"A reputed private medical college."},
    {"college_name":"Mamata Medical College","city":"Khammam","college_type":"Private","ownership":"Trust","year_established":1998,"total_pg_seats":140,"key_specialties":["MD Medicine","MS Surgery","MD Pediatrics"],"short_description":"A well-known private institution."},
    {"college_name":"Apollo Institute of Medical Sciences","city":"Hyderabad","college_type":"Private","ownership":"Private University","year_established":2012,"total_pg_seats":120,"key_specialties":["MD Medicine","MS Surgery","MD Radiology"],"short_description":"A private institution under Apollo Hospitals."},
    {"college_name":"Deccan College of Medical Sciences","city":"Hyderabad","college_type":"Private","ownership":"Trust","year_established":1984,"total_pg_seats":130,"key_specialties":["MD Medicine","MS Surgery","MD Dermatology"],"short_description":"A reputed private medical college."},
    {"college_name":"Mallareddy Medical College","city":"Hyderabad","college_type":"Private","ownership":"Trust","year_established":2012,"total_pg_seats":120,"key_specialties":["MD Medicine","MS Surgery","MD Pathology"],"short_description":"A growing private medical college."}
  ]},
  {"state":"Tripura","colleges":[
    {"college_name":"Agartala Government Medical College","city":"Agartala","college_type":"Government","ownership":"State Govt","year_established":2005,"total_pg_seats":100,"key_specialties":["MD General Medicine","MS General Surgery","MD Pediatrics"],"short_description":"The primary government medical college in Tripura."}
  ]},
  {"state":"Uttar Pradesh","colleges":[
    {"college_name":"King George's Medical University","city":"Lucknow","college_type":"Government","ownership":"State Govt","year_established":1905,"total_pg_seats":400,"key_specialties":["MD Medicine","MS Surgery","MD Radiology"],"short_description":"One of the top medical universities in India."},
    {"college_name":"Institute of Medical Sciences BHU","city":"Varanasi","college_type":"Government","ownership":"Central Govt","year_established":1960,"total_pg_seats":350,"key_specialties":["MD Medicine","MS Surgery","MD Pediatrics"],"short_description":"A premier central government medical institute under BHU."},
    {"college_name":"JNMC AMU","city":"Aligarh","college_type":"Government","ownership":"Central Govt","year_established":1962,"total_pg_seats":300,"key_specialties":["MD Medicine","MS Surgery","MD Radiology"],"short_description":"A reputed medical college under Aligarh Muslim University."},
    {"college_name":"GSVM Medical College","city":"Kanpur","college_type":"Government","ownership":"State Govt","year_established":1955,"total_pg_seats":250,"key_specialties":["MD Medicine","MS Surgery","MD Pediatrics"],"short_description":"A well-established government medical college."},
    {"college_name":"MLN Medical College","city":"Prayagraj","college_type":"Government","ownership":"State Govt","year_established":1961,"total_pg_seats":220,"key_specialties":["MD Medicine","MS Surgery","MD Obstetrics & Gynecology"],"short_description":"A prominent government medical college."},
    {"college_name":"SN Medical College","city":"Agra","college_type":"Government","ownership":"State Govt","year_established":1939,"total_pg_seats":250,"key_specialties":["MD Medicine","MS Surgery","MD Radiology"],"short_description":"A reputed government institution."},
    {"college_name":"BRD Medical College","city":"Gorakhpur","college_type":"Government","ownership":"State Govt","year_established":1972,"total_pg_seats":180,"key_specialties":["MD Medicine","MS Surgery","MD Pediatrics"],"short_description":"A leading government medical college in eastern UP."},
    {"college_name":"Santosh Medical College","city":"Ghaziabad","college_type":"Deemed","ownership":"Deemed University","year_established":1995,"total_pg_seats":150,"key_specialties":["MD Medicine","MS Surgery","MD Dermatology"],"short_description":"A reputed deemed university medical college."},
    {"college_name":"Subharti Medical College","city":"Meerut","college_type":"Private","ownership":"Private University","year_established":1996,"total_pg_seats":180,"key_specialties":["MD Medicine","MS Surgery","MD Pediatrics"],"short_description":"A well-known private medical college."},
    {"college_name":"Era's Lucknow Medical College","city":"Lucknow","college_type":"Private","ownership":"Private University","year_established":2001,"total_pg_seats":150,"key_specialties":["MD Medicine","MS Surgery","MD Pathology"],"short_description":"A reputed private institution."}
  ]},
  {"state":"Uttarakhand","colleges":[
    {"college_name":"AIIMS Rishikesh","city":"Rishikesh","college_type":"Government","ownership":"Central Govt (INI)","year_established":2012,"total_pg_seats":150,"key_specialties":["MD General Medicine","MS General Surgery","MD Radiology"],"short_description":"An Institute of National Importance with strong academic ecosystem."},
    {"college_name":"Government Medical College Haldwani","city":"Haldwani","college_type":"Government","ownership":"State Govt","year_established":2001,"total_pg_seats":120,"key_specialties":["MD Medicine","MS Surgery","MD Pediatrics"],"short_description":"A leading government medical college in Kumaon."},
    {"college_name":"Himalayan Institute of Medical Sciences","city":"Dehradun","college_type":"Deemed","ownership":"Deemed University","year_established":1995,"total_pg_seats":150,"key_specialties":["MD Medicine","MS Surgery","MD Radiology"],"short_description":"A reputed deemed university medical college."},
    {"college_name":"Shri Guru Ram Rai Institute of Medical & Health Sciences","city":"Dehradun","college_type":"Private","ownership":"Private University","year_established":2006,"total_pg_seats":120,"key_specialties":["MD Medicine","MS Surgery","MD Dermatology"],"short_description":"A well-known private medical college."}
  ]},
  {"state":"West Bengal","colleges":[
    {"college_name":"AIIMS Kalyani","city":"Kalyani","college_type":"Government","ownership":"Central Govt (INI)","year_established":2019,"total_pg_seats":50,"key_specialties":["MD Community Medicine","MD Anatomy","MD Physiology"],"short_description":"A newer AIIMS institute."},
    {"college_name":"IPGMER & SSKM Hospital","city":"Kolkata","college_type":"Government","ownership":"State Govt","year_established":1957,"total_pg_seats":300,"key_specialties":["MD General Medicine","MS General Surgery","MD Radiology"],"short_description":"One of the top government medical institutions in eastern India."},
    {"college_name":"Medical College Kolkata","city":"Kolkata","college_type":"Government","ownership":"State Govt","year_established":1835,"total_pg_seats":300,"key_specialties":["MD Medicine","MS Surgery","MD Pediatrics"],"short_description":"The oldest medical college in India."},
    {"college_name":"RG Kar Medical College","city":"Kolkata","college_type":"Government","ownership":"State Govt","year_established":1916,"total_pg_seats":250,"key_specialties":["MD Medicine","MS Surgery","MD Obstetrics & Gynecology"],"short_description":"A reputed government medical college."},
    {"college_name":"Nil Ratan Sircar Medical College","city":"Kolkata","college_type":"Government","ownership":"State Govt","year_established":1873,"total_pg_seats":250,"key_specialties":["MD Medicine","MS Surgery","MD Pediatrics"],"short_description":"A major government medical college in Kolkata."},
    {"college_name":"Calcutta National Medical College","city":"Kolkata","college_type":"Government","ownership":"State Govt","year_established":1948,"total_pg_seats":200,"key_specialties":["MD Medicine","MS Surgery","MD Dermatology"],"short_description":"A well-established government institution."},
    {"college_name":"Bankura Sammilani Medical College","city":"Bankura","college_type":"Government","ownership":"State Govt","year_established":1956,"total_pg_seats":180,"key_specialties":["MD Medicine","MS Surgery","MD Pediatrics"],"short_description":"A reputed government medical college."},
    {"college_name":"Burdwan Medical College","city":"Burdwan","college_type":"Government","ownership":"State Govt","year_established":1969,"total_pg_seats":180,"key_specialties":["MD Medicine","MS Surgery","MD Radiology"],"short_description":"A major government institution in central Bengal."}
  ]},
  {"state":"Chandigarh","colleges":[
    {"college_name":"PGIMER","city":"Chandigarh","college_type":"Government","ownership":"Central Govt (INI)","year_established":1962,"total_pg_seats":300,"key_specialties":["MD General Medicine","MS General Surgery","DM Cardiology"],"short_description":"One of the premier Institutes of National Importance in India."},
    {"college_name":"Government Medical College and Hospital Chandigarh","city":"Chandigarh","college_type":"Government","ownership":"State Govt","year_established":1991,"total_pg_seats":150,"key_specialties":["MD Medicine","MS Surgery","MD Pediatrics"],"short_description":"A well-established government medical college."}
  ]},
  {"state":"Delhi","colleges":[
    {"college_name":"AIIMS New Delhi","city":"New Delhi","college_type":"Government","ownership":"Central Govt (INI)","year_established":1956,"total_pg_seats":450,"key_specialties":["MD General Medicine","MS General Surgery","DM Cardiology"],"short_description":"The top-ranked medical institute in India with global reputation."},
    {"college_name":"Maulana Azad Medical College","city":"New Delhi","college_type":"Government","ownership":"State Govt","year_established":1958,"total_pg_seats":300,"key_specialties":["MD Medicine","MS Surgery","MD Pediatrics"],"short_description":"One of the top government medical colleges in India."},
    {"college_name":"Lady Hardinge Medical College","city":"New Delhi","college_type":"Government","ownership":"Central Govt","year_established":1916,"total_pg_seats":200,"key_specialties":["MD Medicine","MS Obstetrics & Gynecology","MD Pediatrics"],"short_description":"A prestigious government medical college."},
    {"college_name":"UCMS","city":"New Delhi","college_type":"Government","ownership":"Central Govt","year_established":1971,"total_pg_seats":220,"key_specialties":["MD Medicine","MS Surgery","MD Radiology"],"short_description":"A reputed medical college under University of Delhi."},
    {"college_name":"VMMC & Safdarjung Hospital","city":"New Delhi","college_type":"Government","ownership":"Central Govt","year_established":2001,"total_pg_seats":250,"key_specialties":["MD Medicine","MS Surgery","MD Dermatology"],"short_description":"A major government medical college."},
    {"college_name":"Hamdard Institute of Medical Sciences","city":"New Delhi","college_type":"Private","ownership":"Private University","year_established":2012,"total_pg_seats":100,"key_specialties":["MD Medicine","MS Surgery","MD Pathology"],"short_description":"A private medical college under Jamia Hamdard."}
  ]},
  {"state":"Jammu & Kashmir","colleges":[
    {"college_name":"Government Medical College Srinagar","city":"Srinagar","college_type":"Government","ownership":"State Govt","year_established":1959,"total_pg_seats":220,"key_specialties":["MD General Medicine","MS General Surgery","MD Radiology"],"short_description":"A premier government medical college in Kashmir."},
    {"college_name":"Government Medical College Jammu","city":"Jammu","college_type":"Government","ownership":"State Govt","year_established":1973,"total_pg_seats":200,"key_specialties":["MD Medicine","MS Surgery","MD Pediatrics"],"short_description":"A well-established government institution."},
    {"college_name":"SKIMS","city":"Srinagar","college_type":"Government","ownership":"State Govt","year_established":1988,"total_pg_seats":180,"key_specialties":["MD Medicine","MS Surgery","DM Cardiology"],"short_description":"A premier tertiary care institute in J&K."}
  ]},
  {"state":"Puducherry","colleges":[
    {"college_name":"JIPMER","city":"Puducherry","college_type":"Government","ownership":"Central Govt (INI)","year_established":1964,"total_pg_seats":200,"key_specialties":["MD General Medicine","MS General Surgery","DM Cardiology"],"short_description":"A premier Institute of National Importance."},
    {"college_name":"Indira Gandhi Medical College Puducherry","city":"Puducherry","college_type":"Government","ownership":"State Govt","year_established":2010,"total_pg_seats":120,"key_specialties":["MD Medicine","MS Surgery","MD Pediatrics"],"short_description":"A government medical college with growing academic programs."},
    {"college_name":"Mahatma Gandhi Medical College Puducherry","city":"Puducherry","college_type":"Deemed","ownership":"Deemed University","year_established":2006,"total_pg_seats":150,"key_specialties":["MD Medicine","MS Surgery","MD Radiology"],"short_description":"Part of Sri Balaji Vidyapeeth deemed university."}
  ]}
];

const merged = existing.concat(moreStates);
fs.writeFileSync(dataPath, JSON.stringify(merged, null, 2), 'utf-8');
const total = merged.reduce((acc, s) => acc + s.colleges.length, 0);
console.log(`Merged: ${merged.length} states, ${total} colleges total`);
