const { createClient } = require('@supabase/supabase-js');

const SUPABASE_URL = "https://autynwxwiplmuajizwfm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF1dHlud3h3aXBsbXVhaml6d2ZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1Mzk5OTYsImV4cCI6MjA2MDExNTk5Nn0.l8UEWyXi98bn-lPQfGSgY1wFsz4WtW2PtHKR53gq6zE";

const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

const branches = [
  {
    name: "General Medicine", slug: "general-medicine", category: "clinical",
    image_url: "https://images.unsplash.com/photo-1576091160550-2173dad99901?q=80&w=800",
    thumbnail_url: "https://images.unsplash.com/photo-1576091160550-2173dad99901?q=80&w=800",
    banner_url: "https://images.unsplash.com/photo-1579684385127-1ef15d508118?q=80&w=1600",
    difficulty_score: 9, burnout_score: 9, lifestyle_score: 4, earning_score: 7, private_practice_score: 6, future_scope_score: 10,
    saturation_level: "high", seat_availability: "high", demand_level: "high",
    neet_pg_rank_min: 1, neet_pg_rank_max: 3000,
    verdict: "High intellectual satisfaction, but grueling residency. Gateway to DM.",
    consultant_note: "A mandatory stepping stone to lucrative DM branches. Be prepared to study until age 32.",
    pros: ["Ultimate diagnostic authority", "Gateway to elite DM branches", "Recession-proof demand"],
    cons: ["Extremely toxic residency", "High burnout managing chronic patients", "Plain MD is saturating in metros"],
    who_should_choose: ["Deep analytical thinkers", "Students willing to study until age 32+", "Patient-focused doctors"],
    who_should_avoid: ["Students wanting 9-to-5", "Those preferring quick surgical fixes"],
    myths_vs_reality: [{ myth: "Medicine doctors are instantly rich", reality: "Peak earning happens late post-DM." }],
    career_path: ["MD (3 Years)", "SR (1-3 Years)", "DM (3 Years)"],
    fellowships: ["Cardiology", "Neurology", "Gastroenterology"],
    financials: { residency_stipend_range: "₹50k-₹1.2L", first_year_salary: { govt: "₹1L", private: "₹1.2L+" }, five_year_projection: "₹3L", ten_year_projection: "₹8L+", private_practice: { setup_cost: "Low", break_even_years: "1-2 years", scalability: "medium" } }
  },
  {
    name: "Radiology", slug: "radiology", category: "clinical",
    image_url: "https://images.unsplash.com/photo-1516549655169-df83a0774514?q=80&w=800",
    thumbnail_url: "https://images.unsplash.com/photo-1516549655169-df83a0774514?q=80&w=800",
    banner_url: "https://images.unsplash.com/photo-1516549655169-df83a0774514?q=80&w=1600",
    difficulty_score: 7, burnout_score: 4, lifestyle_score: 10, earning_score: 9, private_practice_score: 8, future_scope_score: 9,
    saturation_level: "low", seat_availability: "low", demand_level: "high",
    neet_pg_rank_min: 1, neet_pg_rank_max: 800,
    verdict: "King of lifestyle and early ROI. Excellent startup potential.",
    consultant_note: "If you have the rank, take it. Highest starting salary in all of medicine.",
    pros: ["Zero emergencies", "Highest starting salary", "Clean environment"],
    cons: ["Astronomical setup cost", "Severe eye strain"],
    who_should_choose: ["Tech-savvy visual thinkers", "Lifestyle prioritizers"],
    who_should_avoid: ["Extroverts needing patient gratitude"],
    myths_vs_reality: [{ myth: "AI will replace Radiologists", reality: "AI will assist; volume is growing faster than AI." }],
    career_path: ["MD (3 Years)", "Fellowship", "Consultant"],
    fellowships: ["Interventional", "Neuro", "Fetal Med"],
    financials: { residency_stipend_range: "₹50k-₹1.2L", first_year_salary: { govt: "₹1.2L", private: "₹3L" }, five_year_projection: "₹5L", ten_year_projection: "₹12L+", private_practice: { setup_cost: "Extreme", break_even_years: "5 years", scalability: "high" } }
  },
  {
    name: "General Surgery", slug: "general-surgery", category: "surgical",
    image_url: "https://images.unsplash.com/photo-1551076805-e1869033e561?q=80&w=800",
    thumbnail_url: "https://images.unsplash.com/photo-1551076805-e1869033e561?q=80&w=800",
    banner_url: "https://images.unsplash.com/photo-1559839734-2b71f1536780?q=80&w=1600",
    difficulty_score: 10, burnout_score: 10, lifestyle_score: 2, earning_score: 8, private_practice_score: 5, future_scope_score: 10,
    saturation_level: "high", seat_availability: "medium", demand_level: "high",
    neet_pg_rank_min: 500, neet_pg_rank_max: 5000,
    verdict: "Physically demanding marathon. High respect, requires MCh for metros.",
    consultant_note: "Metros are dominated by specialists. Prepare for a 10-year training curve.",
    pros: ["Instant cure", "Highest respect", "Gateway to MCh"],
    cons: ["Worst WLB", "Physical toll"],
    who_should_choose: ["Action-oriented", "Stamina-heavy"],
    who_should_avoid: ["Weekend lovers"],
    myths_vs_reality: [{ myth: "Surgeons are rich immediately", reality: "Poorly paid until post-MCh." }],
    career_path: ["MS (3 Years)", "MCh (3 Years)"],
    fellowships: ["Urology", "Onco-Surgery"],
    financials: { residency_stipend_range: "₹50k-₹1.2L", first_year_salary: { govt: "₹1L", private: "₹1.2L" }, five_year_projection: "₹3L", ten_year_projection: "₹10L+", private_practice: { setup_cost: "High", break_even_years: "4 years", scalability: "medium" } }
  },
  {
    name: "Pediatrics", slug: "pediatrics", category: "clinical",
    image_url: "https://images.unsplash.com/photo-1502740479091-635887520276?q=80&w=800",
    thumbnail_url: "https://images.unsplash.com/photo-1502740479091-635887520276?q=80&w=800",
    banner_url: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?q=80&w=1600",
    difficulty_score: 8, burnout_score: 8, lifestyle_score: 5, earning_score: 8, private_practice_score: 9, future_scope_score: 9,
    saturation_level: "medium", seat_availability: "high", demand_level: "high",
    neet_pg_rank_min: 1000, neet_pg_rank_max: 5000,
    verdict: "High emotional reward. Safe branch for independent practice.",
    consultant_note: "Vaccination sustains a clinic. Avoid if you can't handle crying children.",
    pros: ["High recovery rate", "Independent practice via vaccines"],
    cons: ["NICU stress", "Anxious parents"],
    who_should_choose: ["Patient individuals"],
    who_should_avoid: ["Emotional sponges"],
    myths_vs_reality: [{ myth: "Medicine for small adults", reality: "Neonate physiology is entirely different." }],
    career_path: ["MD (3 Years)", "Clinic Owner"],
    fellowships: ["Neonatology", "PICU"],
    financials: { residency_stipend_range: "₹50k-₹1.2L", first_year_salary: { govt: "₹1L", private: "₹1.5L" }, five_year_projection: "₹4L", ten_year_projection: "₹10L+", private_practice: { setup_cost: "Low", break_even_years: "2 years", scalability: "high" } }
  },
  {
    name: "Dermatology", slug: "dermatology", category: "clinical",
    image_url: "https://images.unsplash.com/photo-1584515933487-779824d29309?q=80&w=800",
    thumbnail_url: "https://images.unsplash.com/photo-1584515933487-779824d29309?q=80&w=800",
    banner_url: "https://images.unsplash.com/photo-1515377905703-c4788e51af15?q=80&w=1600",
    difficulty_score: 4, burnout_score: 2, lifestyle_score: 10, earning_score: 10, private_practice_score: 10, future_scope_score: 10,
    saturation_level: "high", seat_availability: "low", demand_level: "high",
    neet_pg_rank_min: 1, neet_pg_rank_max: 500,
    verdict: "Best lifestyle. Uncapped income via cosmetology.",
    consultant_note: "Be half-doctor, half-entrepreneur to scale.",
    pros: ["Zero emergencies", "Cosmetology income", "WLB"],
    cons: ["High laser equipment cost"],
    who_should_choose: ["Lifestyle seekers", "Entrepreneurs"],
    who_should_avoid: ["Adrenaline junkies"],
    myths_vs_reality: [{ myth: "Only treat acne", reality: "Residency involves Leprosy, STDs." }],
    career_path: ["MD (3 Years)", "Aesthetic Practice"],
    fellowships: ["Aesthetics", "Trichology"],
    financials: { residency_stipend_range: "₹50k-₹1.2L", first_year_salary: { govt: "₹1L", private: "₹2L" }, five_year_projection: "₹6L", ten_year_projection: "₹25L+", private_practice: { setup_cost: "High", break_even_years: "3 years", scalability: "high" } }
  },
  {
    name: "OBGYN", slug: "obgyn", category: "surgical",
    image_url: "https://images.unsplash.com/photo-1579684385127-1ef15d508118?q=80&w=800",
    thumbnail_url: "https://images.unsplash.com/photo-1579684385127-1ef15d508118?q=80&w=800",
    banner_url: "https://images.unsplash.com/photo-1551076805-e1869033e561?q=80&w=1600",
    difficulty_score: 9, burnout_score: 10, lifestyle_score: 1, earning_score: 9, private_practice_score: 10, future_scope_score: 10,
    saturation_level: "medium", seat_availability: "high", demand_level: "high",
    neet_pg_rank_min: 1000, neet_pg_rank_max: 4000,
    verdict: "Highest volume. Lucrative IVF scope. Severe sleep deprivation.",
    consultant_note: "Maternity homes succeed anywhere. Babies don't wait for sunrise.",
    pros: ["Recession-proof", "Highest patient volume", "IVF income"],
    cons: ["Worst WLB", "High legal risk"],
    who_should_choose: ["High-energy multitaskers"],
    who_should_avoid: ["Sleep prioritizers"],
    myths_vs_reality: [{ myth: "Delivering babies only", reality: "Complex surgeries like hysterectomies." }],
    career_path: ["MS (3 Years)", "IVF Practice"],
    fellowships: ["IVF", "Laparoscopy"],
    financials: { residency_stipend_range: "₹50k-₹1.2L", first_year_salary: { govt: "₹1L", private: "₹1.5L" }, five_year_projection: "₹5L", ten_year_projection: "₹15L+", private_practice: { setup_cost: "High", break_even_years: "4 years", scalability: "high" } }
  },
  {
    name: "Orthopedics", slug: "orthopedics", category: "surgical",
    image_url: "https://images.unsplash.com/photo-1586773860418-d37222d8fce3?q=80&w=800",
    thumbnail_url: "https://images.unsplash.com/photo-1586773860418-d37222d8fce3?q=80&w=800",
    banner_url: "https://images.unsplash.com/photo-1512678080530-7760d81faba6?q=80&w=1600",
    difficulty_score: 8, burnout_score: 6, lifestyle_score: 5, earning_score: 9, private_practice_score: 8, future_scope_score: 9,
    saturation_level: "medium", seat_availability: "high", demand_level: "high",
    neet_pg_rank_min: 2000, neet_pg_rank_max: 6000,
    verdict: "High-action surgical branch via implants. Physically demanding.",
    consultant_note: "Instant results via joint replacements. Massive implant margins.",
    pros: ["Instant gratification", "High implant income"],
    cons: ["Physically exhausting", "Radiation exposure"],
    who_should_choose: ["Action-oriented", "Physical strength"],
    who_should_avoid: ["Radiation-avoidant"],
    myths_vs_reality: [{ myth: "Brute strength only", reality: "Leverage and technique are key." }],
    career_path: ["MS (3 Years)", "Fellowship"],
    fellowships: ["Joint Replacement", "Spine"],
    financials: { residency_stipend_range: "₹50k-₹1.2L", first_year_salary: { govt: "₹1L", private: "₹1.5L" }, five_year_projection: "₹5L", ten_year_projection: "₹15L+", private_practice: { setup_cost: "Moderate", break_even_years: "3 years", scalability: "high" } }
  },
  {
    name: "Anesthesiology", slug: "anesthesiology", category: "clinical",
    image_url: "https://images.unsplash.com/photo-1581056771107-24ca5f033842?q=80&w=800",
    thumbnail_url: "https://images.unsplash.com/photo-1581056771107-24ca5f033842?q=80&w=800",
    banner_url: "https://images.unsplash.com/photo-1551076805-e1869033e561?q=80&w=1600",
    difficulty_score: 8, burnout_score: 7, lifestyle_score: 6, earning_score: 7, private_practice_score: 2, future_scope_score: 9,
    saturation_level: "medium", seat_availability: "high", demand_level: "high",
    neet_pg_rank_min: 5000, neet_pg_rank_max: 15000,
    verdict: "Unsung OT heroes. High adrenaline. No independent OPD.",
    consultant_note: "Love OT but hate follow-ups. No recognition; patients won't know your name.",
    pros: ["Critical care action", "Shift based", "Freelance scope"],
    cons: ["Zero recognition", "Surgeon dependence"],
    who_should_choose: ["Calm under pressure"],
    who_should_avoid: ["Ego-driven spotlight seekers"],
    myths_vs_reality: [{ myth: "Just putting people to sleep", reality: "Keeping patients alive while surgeons inflict trauma." }],
    career_path: ["MD (3 Years)", "Freelance Consultant"],
    fellowships: ["Critical Care", "Pain Med"],
    financials: { residency_stipend_range: "₹50k-₹1.2L", first_year_salary: { govt: "₹1L", private: "₹1.5L" }, five_year_projection: "₹3L", ten_year_projection: "₹6L+", private_practice: { setup_cost: "N/A", break_even_years: "N/A", scalability: "low" } }
  },
  {
    name: "Psychiatry", slug: "psychiatry", category: "clinical",
    image_url: "https://images.unsplash.com/photo-1527613426406-0925c483f9ab?q=80&w=800",
    thumbnail_url: "https://images.unsplash.com/photo-1527613426406-0925c483f9ab?q=80&w=800",
    banner_url: "https://images.unsplash.com/photo-1579154235823-608179b5d1bb?q=80&w=1600",
    difficulty_score: 5, burnout_score: 7, lifestyle_score: 9, earning_score: 6, private_practice_score: 10, future_scope_score: 10,
    saturation_level: "low", seat_availability: "medium", demand_level: "high",
    neet_pg_rank_min: 3000, neet_pg_rank_max: 9000,
    verdict: "Branch of the future. Zero physical exhaustion.",
    consultant_note: "Next big pandemic. Zero setup cost for practice.",
    pros: ["WLB", "Zero setup cost", "Intellectually stimulating"],
    cons: ["Compassion fatigue", "Social stigma"],
    who_should_choose: ["Deep thinkers", "9-to-5 life seekers"],
    who_should_avoid: ["Adrenaline junkies"],
    myths_vs_reality: [{ myth: "Just talking to people", reality: "Heavy pharmacological management of brain chemistry." }],
    career_path: ["MD (3 Years)", "Clinic Owner"],
    fellowships: ["Child Psych", "Addiction Med"],
    financials: { residency_stipend_range: "₹50k-₹1.2L", first_year_salary: { govt: "₹1L", private: "₹1.2L" }, five_year_projection: "₹3L", ten_year_projection: "₹8L+", private_practice: { setup_cost: "Lowest", break_even_years: "1 year", scalability: "medium" } }
  },
  {
    name: "Ophthalmology", slug: "ophthalmology", category: "surgical",
    image_url: "https://images.unsplash.com/photo-1576089297298-500f40bfb72a?q=80&w=800",
    thumbnail_url: "https://images.unsplash.com/photo-1576089297298-500f40bfb72a?q=80&w=800",
    banner_url: "https://images.unsplash.com/photo-1581056771107-24ca5f033842?q=80&w=1600",
    difficulty_score: 4, burnout_score: 3, lifestyle_score: 9, earning_score: 8, private_practice_score: 9, future_scope_score: 8,
    saturation_level: "high", seat_availability: "medium", demand_level: "medium",
    neet_pg_rank_min: 4000, neet_pg_rank_max: 10000,
    verdict: "Clean micro-surgical branch. Zero mortality.",
    consultant_note: "Surgical satisfaction without life-or-death stress.",
    pros: ["Zero mortality", "WLB", "Micro-surgery"],
    cons: ["High setup cost"],
    who_should_choose: ["Perfectionists", "Fine motor skills"],
    who_should_avoid: ["Hand tremors"],
    myths_vs_reality: [{ myth: "Prescribing glasses only", reality: "Highly skilled micro-surgical science." }],
    career_path: ["MS (3 Years)", "Eye Center Owner"],
    fellowships: ["Cataract", "Retina"],
    financials: { residency_stipend_range: "₹50k-₹1.2L", first_year_salary: { govt: "₹1L", private: "₹1.2L" }, five_year_projection: "₹4L", ten_year_projection: "₹12L+", private_practice: { setup_cost: "High", break_even_years: "3 years", scalability: "high" } }
  },
  {
    name: "ENT", slug: "ent", category: "surgical",
    image_url: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?q=80&w=800",
    thumbnail_url: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?q=80&w=800",
    banner_url: "https://images.unsplash.com/photo-1581056771107-24ca5f033842?q=80&w=1600",
    difficulty_score: 5, burnout_score: 4, lifestyle_score: 8, earning_score: 7, private_practice_score: 8, future_scope_score: 8,
    saturation_level: "medium", seat_availability: "medium", demand_level: "medium",
    neet_pg_rank_min: 5000, neet_pg_rank_max: 12000,
    verdict: "Balanced micro-surgical branch. Mix of OPD and OT.",
    consultant_note: "Underrated. Great OPD mix. Buy expensive endoscopes.",
    pros: ["WLB", "Medical-Surgical mix"],
    cons: ["Narrow anatomical field"],
    who_should_choose: ["Detail-oriented", "Endoscopy lovers"],
    who_should_avoid: ["Open surgery lovers"],
    myths_vs_reality: [{ myth: "Tonsils and wax only", reality: "Complex skull base brain surgery." }],
    career_path: ["MS (3 Years)", "Consultant Surgeon"],
    fellowships: ["Onco-Head-Neck", "Cochlear"],
    financials: { residency_stipend_range: "₹50k-₹1.2L", first_year_salary: { govt: "₹1L", private: "₹1.2L" }, five_year_projection: "₹4L", ten_year_projection: "₹8L+", private_practice: { setup_cost: "Moderate", break_even_years: "3 years", scalability: "medium" } }
  },
  {
    name: "Pathology", slug: "pathology", category: "non_clinical",
    image_url: "https://images.unsplash.com/photo-1579154235602-3c3755f949c8?q=80&w=800",
    thumbnail_url: "https://images.unsplash.com/photo-1579154235602-3c3755f949c8?q=80&w=800",
    banner_url: "https://images.unsplash.com/photo-1579154235823-608179b5d1bb?q=80&w=1600",
    difficulty_score: 6, burnout_score: 3, lifestyle_score: 9, earning_score: 5, private_practice_score: 6, future_scope_score: 7,
    saturation_level: "low", seat_availability: "high", demand_level: "medium",
    neet_pg_rank_min: 15000, neet_pg_rank_max: 30000,
    verdict: "Diagnostic backbone. 9-to-5 lifestyle.",
    consultant_note: "Love science but hate patient chaos. Corporate lab monopoly risk.",
    pros: ["WLB", "Zero conflict", "Intellectual satisfaction"],
    cons: ["Lower salary", "Corporate monopolies"],
    who_should_choose: ["Introverts", "Academically inclined"],
    who_should_avoid: ["Action seekers"],
    myths_vs_reality: [{ myth: "Only autopsies", reality: "95% work is diagnosing biopsies." }],
    career_path: ["MD (3 Years)", "Lab Consultant"],
    fellowships: ["Onco-path", "Hematopath"],
    financials: { residency_stipend_range: "₹50k-₹1.2L", first_year_salary: { govt: "₹80k", private: "₹1.2L" }, five_year_projection: "₹2.5L", ten_year_projection: "₹5L+", private_practice: { setup_cost: "Moderate", break_even_years: "5 years", scalability: "low" } }
  },
  {
    name: "Respiratory Medicine", slug: "respiratory-medicine", category: "clinical",
    image_url: "https://images.unsplash.com/photo-1584516150909-c43483ee7932?q=80&w=800",
    thumbnail_url: "https://images.unsplash.com/photo-1584516150909-c43483ee7932?q=80&w=800",
    banner_url: "https://images.unsplash.com/photo-1530497610245-94d3c16cda28?q=80&w=1600",
    difficulty_score: 7, burnout_score: 6, lifestyle_score: 6, earning_score: 8, private_practice_score: 8, future_scope_score: 9,
    saturation_level: "low", seat_availability: "medium", demand_level: "high",
    neet_pg_rank_min: 3000, neet_pg_rank_max: 8000,
    verdict: "High growth post-COVID. Mix of medicine and procedures.",
    consultant_note: "Fantastic Medicine alternative. No DM needed for specialist status.",
    pros: ["Fast track specialization", "OPD-ICU mix"],
    cons: ["TB exposure"],
    who_should_choose: ["Procedure lovers"],
    who_should_avoid: ["Infection fearers"],
    myths_vs_reality: [{ myth: "Treating TB only", reality: "Sleep Medicine, Asthma, Critical Care." }],
    career_path: ["MD", "Consultant Pulmonologist"],
    fellowships: ["Interventional Pulmo"],
    financials: { residency_stipend_range: "₹50k-₹1L", first_year_salary: { govt: "₹1L", private: "₹1.5L" }, five_year_projection: "₹4L", ten_year_projection: "₹8L+", private_practice: { setup_cost: "Moderate", break_even_years: "2 years", scalability: "high" } }
  },
  {
    name: "Emergency Medicine", slug: "emergency-medicine", category: "clinical",
    image_url: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?q=80&w=800",
    thumbnail_url: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?q=80&w=800",
    banner_url: "https://images.unsplash.com/photo-1516549655169-df83a0774514?q=80&w=1600",
    difficulty_score: 9, burnout_score: 10, lifestyle_score: 3, earning_score: 7, private_practice_score: 1, future_scope_score: 10,
    saturation_level: "low", seat_availability: "low", demand_level: "high",
    neet_pg_rank_min: 5000, neet_pg_rank_max: 12000,
    verdict: "Pure adrenaline. Shift work life. Corporate demand skyrocketing.",
    consultant_note: "Tied to corporate ER forever. No independent clinic scope.",
    pros: ["Zero follow-ups", "Adrenaline"],
    cons: ["Extreme burnout", "Shift work forever"],
    who_should_choose: ["Quick deciders"],
    who_should_avoid: ["Family life prioritizers"],
    myths_vs_reality: [{ myth: "Relaxed shift job", reality: "Chaotic first line for emergencies." }],
    career_path: ["MD", "ER Head"],
    fellowships: ["Toxicology"],
    financials: { residency_stipend_range: "₹50k-₹1L", first_year_salary: { govt: "₹1L", private: "₹1.8L" }, five_year_projection: "₹4L", ten_year_projection: "₹8L+", private_practice: { setup_cost: "N/A", break_even_years: "N/A", scalability: "low" } }
  },
  {
    name: "Community Medicine", slug: "psm", category: "non_clinical",
    image_url: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?q=80&w=800",
    thumbnail_url: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?q=80&w=800",
    banner_url: "https://images.unsplash.com/photo-1581056771107-24ca5f033842?q=80&w=1600",
    difficulty_score: 3, burnout_score: 2, lifestyle_score: 10, earning_score: 4, private_practice_score: 1, future_scope_score: 7,
    saturation_level: "high", seat_availability: "high", demand_level: "low",
    neet_pg_rank_min: 25000, neet_pg_rank_max: 45000,
    verdict: "WHO roles and policy making. Fixed govt hours.",
    consultant_note: "IAS equivalent in healthcare. Policy focused.",
    pros: ["Job security", "WHO scope", "10/10 WLB"],
    cons: ["Lowest clinical salary"],
    who_should_choose: ["Public health lovers"],
    who_should_avoid: ["Action seekers"],
    myths_vs_reality: [{ myth: "PSM don't earn", reality: "WHO consultants earn massive pay." }],
    career_path: ["MD", "Professor / WHO Consultant"],
    fellowships: ["Epidemiology"],
    financials: { residency_stipend_range: "₹50k-₹1L", first_year_salary: { govt: "₹80k", private: "₹60k" }, five_year_projection: "₹1.5L", ten_year_projection: "₹4L+", private_practice: { setup_cost: "N/A", break_even_years: "N/A", scalability: "low" } }
  },
  {
    name: "Radiation Oncology", slug: "radiation-oncology", category: "clinical",
    image_url: "https://images.unsplash.com/photo-1551884170-09fb70a3a2ed?q=80&w=800",
    thumbnail_url: "https://images.unsplash.com/photo-1551884170-09fb70a3a2ed?q=80&w=800",
    banner_url: "https://images.unsplash.com/photo-1516549655169-df83a0774514?q=80&w=1600",
    difficulty_score: 6, burnout_score: 5, lifestyle_score: 8, earning_score: 7, private_practice_score: 2, future_scope_score: 9,
    saturation_level: "low", seat_availability: "medium", demand_level: "medium",
    neet_pg_rank_min: 8000, neet_pg_rank_max: 18000,
    verdict: "High-tech oncology. Corporate employee for life.",
    consultant_note: "Tech-heavy. Machines cost ₹15Cr+; you'll be a corporate asset.",
    pros: ["Clean work", "High tech"],
    cons: ["No private setup", "Depressing outcomes"],
    who_should_choose: ["Tech lovers"],
    who_should_avoid: ["Independent clinic seekers"],
    myths_vs_reality: [{ myth: "Radiation risk", reality: "Safest due to strict guidelines." }],
    career_path: ["MD", "Corporate Consultant"],
    fellowships: ["Stereotactic Radiosurgery"],
    financials: { residency_stipend_range: "₹50k-₹1L", first_year_salary: { govt: "₹1L", private: "₹1.8L" }, five_year_projection: "₹4L", ten_year_projection: "₹8L+", private_practice: { setup_cost: "₹15Cr+", break_even_years: "10+ years", scalability: "low" } }
  },
  {
    name: "Forensic Medicine", slug: "forensic-medicine", category: "non_clinical",
    image_url: "https://images.unsplash.com/photo-1582719471327-593255047535?q=80&w=800",
    thumbnail_url: "https://images.unsplash.com/photo-1582719471327-593255047535?q=80&w=800",
    banner_url: "https://images.unsplash.com/photo-1579154235823-608179b5d1bb?q=80&w=1600",
    difficulty_score: 5, burnout_score: 4, lifestyle_score: 9, earning_score: 5, private_practice_score: 1, future_scope_score: 6,
    saturation_level: "low", seat_availability: "high", demand_level: "low",
    neet_pg_rank_min: 20000, neet_pg_rank_max: 40000,
    verdict: "Academic and medico-legal. Zero patient interaction.",
    consultant_note: "Mortuaries and courtrooms. Govt tenure scope.",
    pros: ["Fixed hours", "Court expert status"],
    cons: ["Psychologically heavy"],
    who_should_choose: ["Legal-minded doctors"],
    who_should_avoid: ["Patient-lovers"],
    myths_vs_reality: [{ myth: "It's like CSI", reality: "Paperwork and bureaucratic protocols." }],
    career_path: ["MD", "Professor / Govt Officer"],
    fellowships: ["Toxicology"],
    financials: { residency_stipend_range: "₹50k-₹1L", first_year_salary: { govt: "₹90k", private: "₹70k" }, five_year_projection: "₹1.5L", ten_year_projection: "₹3L+", private_practice: { setup_cost: "N/A", break_even_years: "N/A", scalability: "low" } }
  },
  {
    name: "Microbiology", slug: "microbiology", category: "non_clinical",
    image_url: "https://images.unsplash.com/photo-1581093588401-fbb62a02f120?q=80&w=800",
    thumbnail_url: "https://images.unsplash.com/photo-1581093588401-fbb62a02f120?q=80&w=800",
    banner_url: "https://images.unsplash.com/photo-1579154235823-608179b5d1bb?q=80&w=1600",
    difficulty_score: 6, burnout_score: 3, lifestyle_score: 9, earning_score: 5, private_practice_score: 4, future_scope_score: 7,
    saturation_level: "medium", seat_availability: "high", demand_level: "medium",
    neet_pg_rank_min: 15000, neet_pg_rank_max: 35000,
    verdict: "Essential diagnostic branch. Infection control focus.",
    consultant_note: "Antibiotic policy management. Corporate demand growing.",
    pros: ["Academic lifestyle", "Infection control roles"],
    cons: ["Repetitive lab work"],
    who_should_choose: ["Researchers"],
    who_should_avoid: ["Action seekers"],
    myths_vs_reality: [{ myth: "Just seeing slides", reality: "Managing hospital antibiotic policies." }],
    career_path: ["MD", "Infection Control Head"],
    fellowships: ["Virology"],
    financials: { residency_stipend_range: "₹50k-₹1L", first_year_salary: { govt: "₹80k", private: "₹1.2L" }, five_year_projection: "₹2L", ten_year_projection: "₹5L+", private_practice: { setup_cost: "Moderate", break_even_years: "3 years", scalability: "low" } }
  },
  {
    name: "Pharmacology", slug: "pharmacology", category: "non_clinical",
    image_url: "https://images.unsplash.com/photo-1587854692152-cbe660dbbb88?q=80&w=800",
    thumbnail_url: "https://images.unsplash.com/photo-1587854692152-cbe660dbbb88?q=80&w=800",
    banner_url: "https://images.unsplash.com/photo-1579154235823-608179b5d1bb?q=80&w=1600",
    difficulty_score: 7, burnout_score: 2, lifestyle_score: 10, earning_score: 6, private_practice_score: 2, future_scope_score: 9,
    saturation_level: "low", seat_availability: "high", demand_level: "high",
    neet_pg_rank_min: 10000, neet_pg_rank_max: 30000,
    verdict: "Bridge to Pharma industry. High corporate growth.",
    consultant_note: "Clinical trial management. Corporate salaries can be massive.",
    pros: ["Highest lifestyle", "Corporate growth"],
    cons: ["Zero clinical practice"],
    who_should_choose: ["Industry-minded doctors"],
    who_should_avoid: ["Patient-lovers"],
    myths_vs_reality: [{ myth: "Learning drug names", reality: "Managing million-dollar clinical trials." }],
    career_path: ["MD", "Pharma Medical Advisor"],
    fellowships: ["Clinical Research"],
    financials: { residency_stipend_range: "₹50k-₹1L", first_year_salary: { govt: "₹80k", private: "₹1.8L" }, five_year_projection: "₹4L", ten_year_projection: "₹12L+", private_practice: { setup_cost: "N/A", break_even_years: "N/A", scalability: "low" } }
  },
  {
    name: "Anatomy", slug: "anatomy", category: "non_clinical",
    image_url: "https://images.unsplash.com/photo-1530213786676-41ad9f7736f6?q=80&w=800",
    thumbnail_url: "https://images.unsplash.com/photo-1530213786676-41ad9f7736f6?q=80&w=800",
    banner_url: "https://images.unsplash.com/photo-1579154235823-608179b5d1bb?q=80&w=1600",
    difficulty_score: 8, burnout_score: 1, lifestyle_score: 10, earning_score: 4, private_practice_score: 1, future_scope_score: 5,
    saturation_level: "high", seat_availability: "high", demand_level: "low",
    neet_pg_rank_min: 30000, neet_pg_rank_max: 60000,
    verdict: "Purely academic. Teaching focus.",
    consultant_note: "Best for zero stress medical college career.",
    pros: ["Zero stress", "Teaching satisfaction"],
    cons: ["Lowest income potential"],
    who_should_choose: ["Teachers"],
    who_should_avoid: ["Ambitious earners"],
    myths_vs_reality: [{ myth: "Failed candidates only", reality: "Requires incredible memory." }],
    career_path: ["MD", "Professor"],
    fellowships: ["Genetics"],
    financials: { residency_stipend_range: "₹50k-₹1L", first_year_salary: { govt: "₹80k", private: "₹60k" }, five_year_projection: "₹1.5L", ten_year_projection: "₹3L", private_practice: { setup_cost: "N/A", break_even_years: "N/A", scalability: "low" } }
  },
  {
    name: "Physiology", slug: "physiology", category: "non_clinical",
    image_url: "https://images.unsplash.com/photo-1532187875605-1398863484f9?q=80&w=800",
    thumbnail_url: "https://images.unsplash.com/photo-1532187875605-1398863484f9?q=80&w=800",
    banner_url: "https://images.unsplash.com/photo-1579154235823-608179b5d1bb?q=80&w=1600",
    difficulty_score: 8, burnout_score: 1, lifestyle_score: 10, earning_score: 4, private_practice_score: 1, future_scope_score: 6,
    saturation_level: "high", seat_availability: "high", demand_level: "low",
    neet_pg_rank_min: 30000, neet_pg_rank_max: 60000,
    verdict: "Academic teaching career focus.",
    consultant_note: "Foundation of medicine. Zero stress.",
    pros: ["Stress-free", "Fixed hours"],
    cons: ["Low salary"],
    who_should_choose: ["Academics"],
    who_should_avoid: ["Action seekers"],
    myths_vs_reality: [{ myth: "Easy subject", reality: "Deep biophysics involved." }],
    career_path: ["MD", "Professor"],
    fellowships: ["Neurophysiology"],
    financials: { residency_stipend_range: "₹50k-₹1L", first_year_salary: { govt: "₹80k", private: "₹60k" }, five_year_projection: "₹1.5L", ten_year_projection: "₹3L", private_practice: { setup_cost: "N/A", break_even_years: "N/A", scalability: "low" } }
  },
  {
    name: "Biochemistry", slug: "biochemistry", category: "non_clinical",
    image_url: "https://images.unsplash.com/photo-1532187875605-1398863484f9?q=80&w=800",
    thumbnail_url: "https://images.unsplash.com/photo-1532187875605-1398863484f9?q=80&w=800",
    banner_url: "https://images.unsplash.com/photo-1579154235823-608179b5d1bb?q=80&w=1600",
    difficulty_score: 9, burnout_score: 2, lifestyle_score: 9, earning_score: 6, private_practice_score: 5, future_scope_score: 8,
    saturation_level: "medium", seat_availability: "high", demand_level: "medium",
    neet_pg_rank_min: 25000, neet_pg_rank_max: 50000,
    verdict: "Corporate lab demand. Tech-chemistry focus.",
    consultant_note: "Lucrative diagnostic lab director roles.",
    pros: ["Corporate demand", "High tech"],
    cons: ["No patient interaction"],
    who_should_choose: ["Tech lovers"],
    who_should_avoid: ["Patient-lovers"],
    myths_vs_reality: [{ myth: "Just blood tests", reality: "DNA testing and molecular diagnostics." }],
    career_path: ["MD", "Lab Director"],
    fellowships: ["Genetics"],
    financials: { residency_stipend_range: "₹50k-₹1L", first_year_salary: { govt: "₹80k", private: "₹1.5L" }, five_year_projection: "₹3L", ten_year_projection: "₹6L+", private_practice: { setup_cost: "High", break_even_years: "4 years", scalability: "medium" } }
  },
  {
    name: "Transfusion Medicine", slug: "transfusion-medicine", category: "clinical",
    image_url: "https://images.unsplash.com/photo-1536856780183-09559c3a3721?q=80&w=800",
    thumbnail_url: "https://images.unsplash.com/photo-1536856780183-09559c3a3721?q=80&w=800",
    banner_url: "https://images.unsplash.com/photo-1516549655169-df83a0774514?q=80&w=1600",
    difficulty_score: 5, burnout_score: 3, lifestyle_score: 9, earning_score: 7, private_practice_score: 1, future_scope_score: 8,
    saturation_level: "low", seat_availability: "low", demand_level: "high",
    neet_pg_rank_min: 12000, neet_pg_rank_max: 25000,
    verdict: "Highly specialized. Blood Bank management.",
    consultant_note: "Every major hospital needs one. Zero competition.",
    pros: ["Unique niche", "Stable corporate life"],
    cons: ["No private clinic"],
    who_should_choose: ["Niche hunters"],
    who_should_avoid: ["Independent practice seekers"],
    myths_vs_reality: [{ myth: "Just blood donation", reality: "Advanced cell therapies." }],
    career_path: ["MD", "Blood Bank Director"],
    fellowships: ["Immunology"],
    financials: { residency_stipend_range: "₹50k-₹1L", first_year_salary: { govt: "₹1L", private: "₹1.8L" }, five_year_projection: "₹3L", ten_year_projection: "₹6L+", private_practice: { setup_cost: "N/A", break_even_years: "N/A", scalability: "low" } }
  },
  {
    name: "Palliative Medicine", slug: "palliative-medicine", category: "clinical",
    image_url: "https://images.unsplash.com/photo-1516574187841-cb9cc2ca948b?q=80&w=800",
    thumbnail_url: "https://images.unsplash.com/photo-1516574187841-cb9cc2ca948b?q=80&w=800",
    banner_url: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?q=80&w=1600",
    difficulty_score: 6, burnout_score: 8, lifestyle_score: 7, earning_score: 6, private_practice_score: 4, future_scope_score: 9,
    saturation_level: "low", seat_availability: "low", demand_level: "high",
    neet_pg_rank_min: 15000, neet_pg_rank_max: 28000,
    verdict: "Emotional care for terminal cases. Growing demand.",
    consultant_note: "Requires extreme emotional maturity.",
    pros: ["Meaningful work", "Niche"],
    cons: ["Emotional toll"],
    who_should_choose: ["Empathetic listeners"],
    who_should_avoid: ["Emotional sponges"],
    myths_vs_reality: [{ myth: "Giving up on patients", reality: "Pain management excellence." }],
    career_path: ["MD", "Consultant"],
    fellowships: ["Pain Med"],
    financials: { residency_stipend_range: "₹50k-₹1L", first_year_salary: { govt: "₹1L", private: "₹1.5L" }, five_year_projection: "₹3L", ten_year_projection: "₹7L+", private_practice: { setup_cost: "Low", break_even_years: "2 years", scalability: "medium" } }
  },
  {
    name: "Geriatric Medicine", slug: "geriatric-medicine", category: "clinical",
    image_url: "https://images.unsplash.com/photo-1516574187841-cb9cc2ca948b?q=80&w=800",
    thumbnail_url: "https://images.unsplash.com/photo-1516574187841-cb9cc2ca948b?q=80&w=800",
    banner_url: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?q=80&w=1600",
    difficulty_score: 7, burnout_score: 6, lifestyle_score: 8, earning_score: 8, private_practice_score: 9, future_scope_score: 10,
    saturation_level: "low", seat_availability: "low", demand_level: "high",
    neet_pg_rank_min: 8000, neet_pg_rank_max: 18000,
    verdict: "Massive growth as population ages.",
    consultant_note: "The 'Medicine of the Future'. High home-visit scope.",
    pros: ["Evergreen demand", "Lifestyle"],
    cons: ["Slow progress in cases"],
    who_should_choose: ["Patient doctors"],
    who_should_avoid: ["Adrenaline seekers"],
    myths_vs_reality: [{ myth: "Just General Medicine", reality: "Complex poly-pharmacy management." }],
    career_path: ["MD", "Senior Consultant"],
    fellowships: ["Dementia Care"],
    financials: { residency_stipend_range: "₹50k-₹1L", first_year_salary: { govt: "₹1L", private: "₹1.8L" }, five_year_projection: "₹4L", ten_year_projection: "₹10L+", private_practice: { setup_cost: "Low", break_even_years: "1 year", scalability: "high" } }
  },
  {
    name: "PMR", slug: "pmr", category: "clinical",
    image_url: "https://images.unsplash.com/photo-1530213786676-41ad9f7736f6?q=80&w=800",
    thumbnail_url: "https://images.unsplash.com/photo-1530213786676-41ad9f7736f6?q=80&w=800",
    banner_url: "https://images.unsplash.com/photo-1512678080530-7760d81faba6?q=80&w=1600",
    difficulty_score: 4, burnout_score: 3, lifestyle_score: 10, earning_score: 7, private_practice_score: 9, future_scope_score: 9,
    saturation_level: "low", seat_availability: "low", demand_level: "high",
    neet_pg_rank_min: 10000, neet_pg_rank_max: 20000,
    verdict: "Restoring function. Best clinical lifestyle.",
    consultant_note: "Lifestyle king of clinical medicine. Zero emergencies.",
    pros: ["Best lifestyle", "Patient gratitude"],
    cons: ["Low surgical scope"],
    who_should_choose: ["Sports med enthusiasts"],
    who_should_avoid: ["Action hunters"],
    myths_vs_reality: [{ myth: "It's just physiotherapy", reality: "Physios follow the PMR doctor's plan." }],
    career_path: ["MD", "Rehab Consultant"],
    fellowships: ["Sports Med"],
    financials: { residency_stipend_range: "₹50k-₹1L", first_year_salary: { govt: "₹1L", private: "₹1.5L" }, five_year_projection: "₹3L", ten_year_projection: "₹8L+", private_practice: { setup_cost: "Moderate", break_even_years: "2 years", scalability: "high" } }
  }
];

async function seedFinalMaster() {
  console.log("🚀 Starting Final Master Seeder (All 26 Branches)...");
  for (const branch of branches) {
    console.log(`Upserting: ${branch.name}`);
    const { error } = await supabase.from('specializations').upsert(branch, { onConflict: 'slug' });
    if (error) console.error(`❌ Error in ${branch.name}:`, error.message);
    else console.log(`✅ Success: ${branch.name}`);
  }
}

seedFinalMaster();
