const { createClient } = require('@supabase/supabase-js');

const SUPABASE_URL = "https://autynwxwiplmuajizwfm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF1dHlud3h3aXBsbXVhaml6d2ZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1Mzk5OTYsImV4cCI6MjA2MDExNTk5Nn0.l8UEWyXi98bn-lPQfGSgY1wFsz4WtW2PtHKR53gq6zE";

const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

const branches = [
  // BATCH 1: Clinical Core
  {
    name: "MD General Medicine", slug: "md-general-medicine", category: "clinical",
    thumbnail_url: "https://images.unsplash.com/photo-1576091160550-2173dad99901?q=80&w=800",
    banner_url: "https://images.unsplash.com/photo-1579684385127-1ef15d508118?q=80&w=1600",
    difficulty_score: 9, burnout_score: 9, lifestyle_score: 4, earning_score: 7, private_practice_score: 6, future_scope_score: 10,
    saturation_level: "high", seat_availability: "high", demand_level: "high",
    neet_pg_rank_min: 1, neet_pg_rank_max: 3000,
    verdict: "High intellectual satisfaction, but grueling residency. A mandatory stepping stone to lucrative DM branches.",
    consultant_note: "Do not take this if you want an easy life in your 30s. A plain MD Medicine struggles in metros today; be prepared to study for another 3 years for your DM to truly reap the financial rewards.",
    pros: ["Ultimate diagnostic authority", "Gateway to elite DM branches", "Recession-proof demand"],
    cons: ["Extremely toxic residency", "High burnout managing chronic patients", "Plain MD is saturating in metros"],
    who_should_choose: ["Deep analytical thinkers", "Students willing to study until age 32+", "Patient-focused doctors"],
    who_should_avoid: ["Students wanting 9-to-5", "Those preferring quick surgical fixes"],
    myths_vs_reality: [{ myth: "Medicine doctors are instantly rich", reality: "Peak earning happens late post-DM." }],
    career_path: ["MD (3 Years)", "SR (1-3 Years)", "DM (3 Years)", "Senior Consultant"],
    fellowships: ["Cardiology", "Neurology", "Gastroenterology"],
    financials: { residency_stipend_range: "₹50k-₹1.2L", first_year_salary: { govt: "₹1L", private: "₹1.2L+" }, five_year_projection: "₹2.5L-₹3.5L (Plain MD)", ten_year_projection: "₹8L+ (With DM)", private_practice: { setup_cost: "Low", break_even_years: "1-2 years", scalability: "medium" } }
  },
  {
    name: "MD Radio-diagnosis", slug: "md-radiology", category: "clinical",
    thumbnail_url: "https://images.unsplash.com/photo-1516549655169-df83a0774514?q=80&w=800",
    banner_url: "https://images.unsplash.com/photo-1516549655169-df83a0774514?q=80&w=1600",
    difficulty_score: 7, burnout_score: 4, lifestyle_score: 10, earning_score: 9, private_practice_score: 8, future_scope_score: 9,
    saturation_level: "low", seat_availability: "low", demand_level: "high",
    neet_pg_rank_min: 1, neet_pg_rank_max: 800,
    verdict: "King of lifestyle and early ROI, but demands massive capital if you want to be your own boss.",
    consultant_note: "If you have the rank, take it. However, if your dream is your own center, ensure you have ₹5Cr+ in backing for MRI/CT. Otherwise, you're a high-paid employee.",
    pros: ["Zero emergencies", "Highest starting salary", "Clean environment"],
    cons: ["Astronomical setup cost", "Severe eye strain", "Isolating; low patient interaction"],
    who_should_choose: ["Tech-savvy visual thinkers", "Lifestyle prioritizers", "Introverts"],
    who_should_avoid: ["Extroverts needing patient gratitude", "Adrenaline junkies"],
    myths_vs_reality: [{ myth: "AI will replace Radiologists", reality: "AI will assist; volume is growing faster than AI." }],
    career_path: ["MD (3 Years)", "Fellowship (1-2 Years)", "Corporate Consultant OR Center Owner"],
    fellowships: ["Interventional Radiology", "Neuro-Radiology", "Fetal Medicine"],
    financials: { residency_stipend_range: "₹50k-₹1.2L", first_year_salary: { govt: "₹1.2L", private: "₹2.5L-₹3.5L" }, five_year_projection: "₹4L-₹6L", ten_year_projection: "₹10L+ (Owner)", private_practice: { setup_cost: "Extreme (₹5Cr+)", break_even_years: "5-8 years", scalability: "high" } }
  },
  {
    name: "MS General Surgery", slug: "ms-general-surgery", category: "surgical",
    thumbnail_url: "https://images.unsplash.com/photo-1551076805-e1869033e561?q=80&w=800",
    banner_url: "https://images.unsplash.com/photo-1559839734-2b71f1536780?q=80&w=1600",
    difficulty_score: 10, burnout_score: 10, lifestyle_score: 2, earning_score: 8, private_practice_score: 5, future_scope_score: 10,
    saturation_level: "high", seat_availability: "medium", demand_level: "high",
    neet_pg_rank_min: 500, neet_pg_rank_max: 5000,
    verdict: "Physically demanding marathon. High adrenaline, requires MCh for metro success.",
    consultant_note: "Metros are now dominated by MCh specialists. Prepare for brutal physical exhaustion and a 10-year training curve.",
    pros: ["Instant cure", "Highest respect", "Gateway to elite MCh"],
    cons: ["Worst WLB", "High legal risk", "Physical toll"],
    who_should_choose: ["Action-oriented", "Stamina-heavy", "Decisive"],
    who_should_avoid: ["Weekend lovers", "Quick ROI seekers"],
    myths_vs_reality: [{ myth: "Surgeons are rich immediately", reality: "Poorly paid until age 33+ post-MCh." }],
    career_path: ["MS (3 Years)", "SR (3 Years)", "MCh (3 Years)", "Corporate Surgeon"],
    fellowships: ["Urology", "Onco-Surgery", "GI Surgery"],
    financials: { residency_stipend_range: "₹50k-₹1.2L", first_year_salary: { govt: "₹1L", private: "₹1.2L" }, five_year_projection: "₹2L-₹3L (Plain MS)", ten_year_projection: "₹8L-₹15L (With MCh)", private_practice: { setup_cost: "High", break_even_years: "3-5 years", scalability: "medium" } }
  },
  // BATCH 2: Clinical Popular
  {
    name: "MD Pediatrics", slug: "md-pediatrics", category: "clinical",
    thumbnail_url: "https://images.unsplash.com/photo-1502740479091-635887520276?q=80&w=800",
    banner_url: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?q=80&w=1600",
    difficulty_score: 8, burnout_score: 8, lifestyle_score: 5, earning_score: 8, private_practice_score: 9, future_scope_score: 9,
    saturation_level: "medium", seat_availability: "high", demand_level: "high",
    neet_pg_rank_min: 1000, neet_pg_rank_max: 5000,
    verdict: "High emotional reward and private practice scope, but physically exhausting NICU duties.",
    consultant_note: "Safe branch for independent practice. Vaccination sustains a clinic. Avoid if you hate crying or can't do precise dosage math.",
    pros: ["High recovery rate", "Independent practice via vaccines", "Emotional fulfillment"],
    cons: ["NICU stress", "Anxious parents", "Dosage math must be perfect"],
    who_should_choose: ["Patient individuals", "Child lovers", "Quick setup seekers"],
    who_should_avoid: ["Emotional trauma absorbers", "Dosage math haters"],
    myths_vs_reality: [{ myth: "Medicine for small adults", reality: "Neonate physiology is entirely different science." }],
    career_path: ["MD (3 Years)", "Fellowship (1-2 Years)", "Consultant / Clinic Owner"],
    fellowships: ["Neonatology", "PICU", "Ped-Neurology"],
    financials: { residency_stipend_range: "₹50k-₹1.2L", first_year_salary: { govt: "₹1L", private: "₹1.5L" }, five_year_projection: "₹3L-₹5L", ten_year_projection: "₹10L+ (Owner)", private_practice: { setup_cost: "Low", break_even_years: "1-2 years", scalability: "high" } }
  },
  {
    name: "MD Dermatology (DVL)", slug: "md-dermatology", category: "clinical",
    thumbnail_url: "https://images.unsplash.com/photo-1584515933487-779824d29309?q=80&w=800",
    banner_url: "https://images.unsplash.com/photo-1515377905703-c4788e51af15?q=80&w=1600",
    difficulty_score: 4, burnout_score: 2, lifestyle_score: 10, earning_score: 10, private_practice_score: 10, future_scope_score: 10,
    saturation_level: "high", seat_availability: "low", demand_level: "high",
    neet_pg_rank_min: 1, neet_pg_rank_max: 500,
    verdict: "Best lifestyle branch. Zero emergencies, massive cosmetic income, but fiercely competitive.",
    consultant_note: "Take it if you get it. Cosmetology pays the big bills. Be half-doctor, half-entrepreneur to scale.",
    pros: ["Zero emergencies", "Uncapped earning via cosmetology", "Work-life balance"],
    cons: ["High laser equipment cost", "Commercialized", "Quacks competition"],
    who_should_choose: ["Lifestyle seekers", "Entrepreneurs", "Aesthetic eye doctors"],
    who_should_avoid: ["Adrenaline junkies", "Business/Marketing haters"],
    myths_vs_reality: [{ myth: "Only treat acne", reality: "Residency involves Leprosy, Pemphigus, STDs." }],
    career_path: ["MD (3 Years)", "Aesthetic Fellowship", "Clinic Owner"],
    fellowships: ["Aesthetics", "Dermatosurgery", "Trichology"],
    financials: { residency_stipend_range: "₹50k-₹1.2L", first_year_salary: { govt: "₹1L", private: "₹1.5L-₹2L" }, five_year_projection: "₹4L-₹8L", ten_year_projection: "₹20L+ (Practice)", private_practice: { setup_cost: "Extreme (₹1Cr+)", break_even_years: "3-5 years", scalability: "high" } }
  },
  {
    name: "MS Obstetrics & Gynaecology", slug: "ms-obgyn", category: "surgical",
    thumbnail_url: "https://images.unsplash.com/photo-1579684385127-1ef15d508118?q=80&w=800",
    banner_url: "https://images.unsplash.com/photo-1551076805-e1869033e561?q=80&w=1600",
    difficulty_score: 9, burnout_score: 10, lifestyle_score: 1, earning_score: 9, private_practice_score: 10, future_scope_score: 10,
    saturation_level: "medium", seat_availability: "high", demand_level: "high",
    neet_pg_rank_min: 1000, neet_pg_rank_max: 4000,
    verdict: "Highest volume and lucrative IVF scope, but destroys sleep schedule.",
    consultant_note: "Robust surgical practice. Maternity homes succeed anywhere. High legal risk; babies don't wait for sunrise.",
    pros: ["Recession-proof", "Highest patient volume", "IVF income potential"],
    cons: ["Worst WLB", "High legal risk", "Sleep deprivation"],
    who_should_choose: ["High-energy multitaskers", "Guaranteed practice seekers"],
    who_should_avoid: ["Sleep prioritizers", "Legal stress haters"],
    myths_vs_reality: [{ myth: "Delivering babies only", reality: "Complex surgeries like hysterectomies and hemorrhage management." }],
    career_path: ["MS (3 Years)", "Fellowship (IVF / Fetal Med)", "Clinic Owner"],
    fellowships: ["IVF", "Fetal Medicine", "Laparoscopy"],
    financials: { residency_stipend_range: "₹50k-₹1.2L", first_year_salary: { govt: "₹1L", private: "₹1.5L" }, five_year_projection: "₹3L-₹5L", ten_year_projection: "₹15L+ (IVF/Maternity)", private_practice: { setup_cost: "High", break_even_years: "3-5 years", scalability: "high" } }
  },
  {
    name: "MS Orthopedics", slug: "ms-orthopedics", category: "surgical",
    thumbnail_url: "https://images.unsplash.com/photo-1586773860418-d37222d8fce3?q=80&w=800",
    banner_url: "https://images.unsplash.com/photo-1512678080530-7760d81faba6?q=80&w=1600",
    difficulty_score: 8, burnout_score: 6, lifestyle_score: 5, earning_score: 9, private_practice_score: 8, future_scope_score: 9,
    saturation_level: "medium", seat_availability: "high", demand_level: "high",
    neet_pg_rank_min: 2000, neet_pg_rank_max: 6000,
    verdict: "High-action surgical branch via implants, physically demanding.",
    consultant_note: "Instant results via joint replacements. Massive implant margins. Be mindful of C-arm radiation.",
    pros: ["Instant gratification", "High implant income", "No terminal illness management"],
    cons: ["Physically exhausting", "Radiation exposure", "Trauma-dependent initially"],
    who_should_choose: ["Action-oriented", "Physical strength", "Biomechanics lovers"],
    who_should_avoid: ["Medical puzzle seekers", "Radiation-avoidant"],
    myths_vs_reality: [{ myth: "Brute strength only", reality: "Leverage and technique are key." }],
    career_path: ["MS (3 Years)", "Fellowship (Arthroplasty)", "Consultant Surgeon"],
    fellowships: ["Joint Replacement", "Sports Med", "Spine"],
    financials: { residency_stipend_range: "₹50k-₹1.2L", first_year_salary: { govt: "₹1L", private: "₹1.5L" }, five_year_projection: "₹3L-₹6L", ten_year_projection: "₹15L+ (Volume)", private_practice: { setup_cost: "Moderate", break_even_years: "2-4 years", scalability: "high" } }
  },
  {
    name: "MD Psychiatry", slug: "md-psychiatry", category: "clinical",
    thumbnail_url: "https://images.unsplash.com/photo-1527613426406-0925c483f9ab?q=80&w=800",
    banner_url: "https://images.unsplash.com/photo-1579154235823-608179b5d1bb?q=80&w=1600",
    difficulty_score: 5, burnout_score: 7, lifestyle_score: 9, earning_score: 6, private_practice_score: 10, future_scope_score: 10,
    saturation_level: "low", seat_availability: "medium", demand_level: "high",
    neet_pg_rank_min: 3000, neet_pg_rank_max: 9000,
    verdict: "Branch of the future. Zero physical exhaustion, high demand, compassion fatigue risk.",
    consultant_note: "Next big pandemic. zero setup cost for practice. Set firm emotional boundaries.",
    pros: ["Work-life balance", "Zero setup cost", "Intellectually stimulating"],
    cons: ["Compassion fatigue", "Slower financial curve", "Social stigma"],
    who_should_choose: ["Deep thinkers", "Empathetic listeners", "9-to-5 life seekers"],
    who_should_avoid: ["Adrenaline junkies", "Instant cure seekers"],
    myths_vs_reality: [{ myth: "Just talking to people", reality: "Heavy pharmacological management of brain chemistry." }],
    career_path: ["MD (3 Years)", "Consultant Psychiatrist"],
    fellowships: ["Child Psychiatry", "Geriatric Psych", "Addiction Med"],
    financials: { residency_stipend_range: "₹50k-₹1.2L", first_year_salary: { govt: "₹1L", private: "₹1.2L" }, five_year_projection: "₹2L-₹4L", ten_year_projection: "₹6L+", private_practice: { setup_cost: "Lowest", break_even_years: "1 year", scalability: "medium" } }
  },
  {
    name: "MD Anesthesiology", slug: "md-anesthesiology", category: "clinical",
    thumbnail_url: "https://images.unsplash.com/photo-1581056771107-24ca5f033842?q=80&w=800",
    banner_url: "https://images.unsplash.com/photo-1551076805-e1869033e561?q=80&w=1600",
    difficulty_score: 8, burnout_score: 7, lifestyle_score: 6, earning_score: 7, private_practice_score: 2, future_scope_score: 9,
    saturation_level: "medium", seat_availability: "high", demand_level: "high",
    neet_pg_rank_min: 5000, neet_pg_rank_max: 15000,
    verdict: "Unsung OT heroes. High adrenaline, instant results, no independent OPD.",
    consultant_note: "Love OT but hate follow-ups. Ego-driven people should avoid; patients won't know your name.",
    pros: ["Critical care action", "Work ends when shift ends", "Freelance scope"],
    cons: ["Zero recognition", "High OT stress", "Surgeon dependence"],
    who_should_choose: ["Calm under pressure", "Pharmacology lovers", "No OPD seekers"],
    who_should_avoid: ["Ego-driven spotlight seekers", "Independent clinic dreamers"],
    myths_vs_reality: [{ myth: "Just putting people to sleep", reality: "Keeping patients alive while surgeons inflict trauma." }],
    career_path: ["MD (3 Years)", "Freelance OR ICU Consultant"],
    fellowships: ["Critical Care", "Pain Med", "Cardiac Anesthesia"],
    financials: { residency_stipend_range: "₹50k-₹1.2L", first_year_salary: { govt: "₹1L", private: "₹1.5L" }, five_year_projection: "₹2.5L-₹4L", ten_year_projection: "₹5L+", private_practice: { setup_cost: "N/A", break_even_years: "N/A", scalability: "low" } }
  },
  // BATCH 3: Specialist Clinical
  {
    name: "MS Ophthalmology", slug: "ms-ophthalmology", category: "surgical",
    thumbnail_url: "https://images.unsplash.com/photo-1576089297298-500f40bfb72a?q=80&w=800",
    banner_url: "https://images.unsplash.com/photo-1581056771107-24ca5f033842?q=80&w=1600",
    difficulty_score: 4, burnout_score: 3, lifestyle_score: 9, earning_score: 8, private_practice_score: 9, future_scope_score: 8,
    saturation_level: "high", seat_availability: "medium", demand_level: "medium",
    neet_pg_rank_min: 4000, neet_pg_rank_max: 10000,
    verdict: "Clean micro-surgical branch. Excellent lifestyle, zero mortality, equipment-heavy.",
    consultant_note: "Surgical satisfaction without life-or-death stress. Must secure Phaco fellowship post-MS.",
    pros: ["Zero mortality", "Work-life balance", "Micro-surgery"],
    cons: ["High setup cost", "Steep learning curve", "Corporate domination"],
    who_should_choose: ["Perfectionists", "Fine motor skills", "Tech lovers"],
    who_should_avoid: ["Adrenaline junkies", "Hand tremors"],
    myths_vs_reality: [{ myth: "Prescribing glasses only", reality: "Highly skilled micro-surgical science." }],
    career_path: ["MS (3 Years)", "Fellowship", "Eye Center Owner"],
    fellowships: ["Cataract", "Retina", "LASIK"],
    financials: { residency_stipend_range: "₹50k-₹1.2L", first_year_salary: { govt: "₹1L", private: "₹1.2L" }, five_year_projection: "₹2.5L-₹4L", ten_year_projection: "₹10L+", private_practice: { setup_cost: "High", break_even_years: "3-5 years", scalability: "high" } }
  },
  {
    name: "MS ENT", slug: "ms-ent", category: "surgical",
    thumbnail_url: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?q=80&w=800",
    banner_url: "https://images.unsplash.com/photo-1581056771107-24ca5f033842?q=80&w=1600",
    difficulty_score: 5, burnout_score: 4, lifestyle_score: 8, earning_score: 7, private_practice_score: 8, future_scope_score: 8,
    saturation_level: "medium", seat_availability: "medium", demand_level: "medium",
    neet_pg_rank_min: 5000, neet_pg_rank_max: 12000,
    verdict: "Balanced micro-surgical branch. Real money in Head & Neck Onco or Cochlear Implants.",
    consultant_note: "Underrated. Great OPD mix. Buy expensive endoscopes for your clinic.",
    pros: ["WLB", "Medical-Surgical mix", "Short surgeries"],
    cons: ["Narrow anatomical field", "Equipment cost", "Referral dependency"],
    who_should_choose: ["Detail-oriented", "Endoscopy lovers", "Balanced life seekers"],
    who_should_avoid: ["Open surgery lovers", "Narrow space haters"],
    myths_vs_reality: [{ myth: "Tonsils and wax only", reality: "Complex skull base brain surgery via nose." }],
    career_path: ["MS (3 Years)", "Fellowship", "Consultant Surgeon"],
    fellowships: ["Onco-Head-Neck", "Cochlear", "FESS"],
    financials: { residency_stipend_range: "₹50k-₹1.2L", first_year_salary: { govt: "₹1L", private: "₹1.2L" }, five_year_projection: "₹2L-₹4L", ten_year_projection: "₹8L+", private_practice: { setup_cost: "Moderate", break_even_years: "2-4 years", scalability: "medium" } }
  },
  {
    name: "MD Pathology", slug: "md-pathology", category: "non_clinical",
    thumbnail_url: "https://images.unsplash.com/photo-1579154235602-3c3755f949c8?q=80&w=800",
    banner_url: "https://images.unsplash.com/photo-1579154235823-608179b5d1bb?q=80&w=1600",
    difficulty_score: 6, burnout_score: 3, lifestyle_score: 9, earning_score: 5, private_practice_score: 6, future_scope_score: 7,
    saturation_level: "low", seat_availability: "high", demand_level: "medium",
    neet_pg_rank_min: 15000, neet_pg_rank_max: 30000,
    verdict: "Diagnostic backbone. 9-to-5 lifestyle, lower starting pay, zero patient interaction.",
    consultant_note: "Love science but hate patient chaos. setting up independent labs is tough due to corporate monopolies.",
    pros: ["WLB", "Zero conflict", "Intellectual satisfaction"],
    cons: ["Lower salary", "No recognition", "Corporate monopolies"],
    who_should_choose: ["Introverts", "Academically inclined"],
    who_should_avoid: ["Extroverts needing gratitude", "Action seekers"],
    myths_vs_reality: [{ myth: "Only autopsies", reality: "95% work is diagnosing biopsies for surgeons." }],
    career_path: ["MD (3 Years)", "Fellowship", "Lab Consultant"],
    fellowships: ["Onco-path", "Hematopath"],
    financials: { residency_stipend_range: "₹50k-₹1.2L", first_year_salary: { govt: "₹80k", private: "₹1L" }, five_year_projection: "₹1.5L-₹2.5L", ten_year_projection: "₹4L+", private_practice: { setup_cost: "Moderate", break_even_years: "4-6 years", scalability: "low" } }
  },
  // BATCH 4: Emerging
  {
    name: "MD Respiratory Medicine", slug: "md-respiratory-medicine", category: "clinical",
    thumbnail_url: "https://images.unsplash.com/photo-1584516150909-c43483ee7932?q=80&w=800",
    banner_url: "https://images.unsplash.com/photo-1530497610245-94d3c16cda28?q=80&w=1600",
    difficulty_score: 7, burnout_score: 6, lifestyle_score: 6, earning_score: 8, private_practice_score: 8, future_scope_score: 9,
    saturation_level: "low", seat_availability: "medium", demand_level: "high",
    neet_pg_rank_min: 3000, neet_pg_rank_max: 8000,
    verdict: "Post-COVID high growth. Mix of medicine and procedures.",
    consultant_note: "Fantastic Medicine alternative. No DM needed for specialization status. Pollution rise guarantees flow.",
    pros: ["Fast track specialization", "Urban demand", "OPD-ICU mix"],
    cons: ["TB exposure", "Depressing outcomes (cancer)", "Emergency stress"],
    who_should_choose: ["General Medicine alternative seekers", "Procedure lovers"],
    who_should_avoid: ["Infection fearers"],
    myths_vs_reality: [{ myth: "Treating TB only", reality: "Sleep Medicine, Asthma, Critical Care." }],
    career_path: ["MD", "Consultant Pulmonologist"],
    fellowships: ["Critical Care", "Interventional Pulmo"],
    financials: { residency_stipend_range: "₹50k-₹1L", first_year_salary: { govt: "₹1L", private: "₹1.5L" }, five_year_projection: "₹3L-₹5L", ten_year_projection: "₹8L+", private_practice: { setup_cost: "Moderate", break_even_years: "2 years", scalability: "high" } }
  },
  {
    name: "MD Emergency Medicine", slug: "md-emergency-medicine", category: "clinical",
    thumbnail_url: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?q=80&w=800",
    banner_url: "https://images.unsplash.com/photo-1516549655169-df83a0774514?q=80&w=1600",
    difficulty_score: 9, burnout_score: 10, lifestyle_score: 3, earning_score: 7, private_practice_score: 1, future_scope_score: 10,
    saturation_level: "low", seat_availability: "low", demand_level: "high",
    neet_pg_rank_min: 5000, neet_pg_rank_max: 12000,
    verdict: "Pure adrenaline, shift work life, high burnout.",
    consultant_note: "Fastest corporate hospital growth. Tied to corporate ER forever; no independent clinic scope.",
    pros: ["Zero follow-ups", "Adrenaline", "Corporate demand"],
    cons: ["Burnout", "Shift work forever", "No private practice"],
    who_should_choose: ["Adrenaline junkies", "Quick deciders"],
    who_should_avoid: ["Family life prioritizers", "Clinic dreamers"],
    myths_vs_reality: [{ myth: "Relaxed shift job", reality: "Chaotic first line for angry relatives." }],
    career_path: ["MD", "ER Head"],
    fellowships: ["Toxicology", "Pre-hospital"],
    financials: { residency_stipend_range: "₹50k-₹1L", first_year_salary: { govt: "₹1L", private: "₹1.5L" }, five_year_projection: "₹3L-₹4L", ten_year_projection: "₹6L+", private_practice: { setup_cost: "N/A", break_even_years: "N/A", scalability: "low" } }
  },
  {
    name: "MD Community Medicine (PSM)", slug: "md-psm", category: "non_clinical",
    thumbnail_url: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?q=80&w=800",
    banner_url: "https://images.unsplash.com/photo-1581056771107-24ca5f033842?q=80&w=1600",
    difficulty_score: 3, burnout_score: 2, lifestyle_score: 10, earning_score: 4, private_practice_score: 1, future_scope_score: 7,
    saturation_level: "high", seat_availability: "high", demand_level: "low",
    neet_pg_rank_min: 25000, neet_pg_rank_max: 45000,
    verdict: "WHO roles and policy making. Terrible for treatment.",
    consultant_note: "IAS equivalent in healthcare. WHO/UNICEF/Professor scope only.",
    pros: ["Job security", "International agency scope", "10/10 WLB"],
    cons: ["Lowest salary", "No clinical skills", "Boring for action seekers"],
    who_should_choose: ["Policy makers", "Public health lovers"],
    who_should_avoid: ["Action seekers", "Money seekers"],
    myths_vs_reality: [{ myth: "PSM don't earn", reality: "WHO consultants earn massive tax-free pay." }],
    career_path: ["MD", "WHO Consultant / Professor"],
    fellowships: ["Epidemiology"],
    financials: { residency_stipend_range: "₹50k-₹1L", first_year_salary: { govt: "₹80k", private: "₹60k" }, five_year_projection: "₹1.5L", ten_year_projection: "₹3L", private_practice: { setup_cost: "N/A", break_even_years: "N/A", scalability: "low" } }
  },
  {
    name: "MD Radiation Oncology", slug: "md-radiation-oncology", category: "clinical",
    thumbnail_url: "https://images.unsplash.com/photo-1551884170-09fb70a3a2ed?q=80&w=800",
    banner_url: "https://images.unsplash.com/photo-1516549655169-df83a0774514?q=80&w=1600",
    difficulty_score: 6, burnout_score: 5, lifestyle_score: 8, earning_score: 7, private_practice_score: 2, future_scope_score: 9,
    saturation_level: "low", seat_availability: "medium", demand_level: "medium",
    neet_pg_rank_min: 8000, neet_pg_rank_max: 18000,
    verdict: "High-tech oncology, corporate employee for life.",
    consultant_note: "Cancer is growing. Tech-heavy. Machines cost ₹15Cr+; you'll never be independent.",
    pros: ["Clean work", "High tech", "Good lifestyle"],
    cons: ["No private setup", "Depressing outcomes", "Narrow field"],
    who_should_choose: ["Tech lovers", "Empathetic doctors"],
    who_should_avoid: ["Independent clinic seekers"],
    myths_vs_reality: [{ myth: "Radiation exposure risk", reality: "Safest due to strict atomic guidelines." }],
    career_path: ["MD", "Corporate Consultant"],
    fellowships: ["Stereotactic Radiosurgery"],
    financials: { residency_stipend_range: "₹50k-₹1L", first_year_salary: { govt: "₹1L", private: "₹1.5L" }, five_year_projection: "₹3L-₹4L", ten_year_projection: "₹6L+", private_practice: { setup_cost: "₹15Cr+", break_even_years: "10+ years", scalability: "low" } }
  }
];

async function seedAll() {
  console.log("🚀 Starting Decision Engine Seeder (ALL 16 V5)...");
  for (const branch of branches) {
    console.log(`Upserting: ${branch.name}`);
    const { error } = await supabase.from('specializations').upsert(branch, { onConflict: 'slug' });
    if (error) console.error(`❌ Error in ${branch.name}:`, error.message);
    else console.log(`✅ Success: ${branch.name}`);
  }
}

seedAll();
